### ISSUE TITLE
24시(00시) 30분부터 1시간까지 서버 오동작 발생.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1026]
Converting circular structure to JSON 가 발생함.

```
info: ## /v000705/town/경기도/성남시분당구/수내1동
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at ServerResponse.json (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/response.js:242:19)
    at ControllerTown24h.sendResult (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/controllers/controllerTown24h.js:554:13)
    at Layer.handle [as handle_request] (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/route.js:131:13)
    at ControllerTown.dataToFixed (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/controllers/controllerTown.js:1558:9)
    at Layer.handle [as handle_request] (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/route.js:131:13)
    at ControllerTown.getSummary (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/controllers/controllerTown.js:1058:9)
    at Layer.handle [as handle_request] (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/route.js:131:13)
    at ControllerTown.insertStrForData (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/controllers/controllerTown.js:1585:9)
    at Layer.handle [as handle_request] (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/route.js:131:13)
    at ControllerTown.insertIndex (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/controllers/controllerTown.js:1530:9)
    at Layer.handle [as handle_request] (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by kimalec** [comment]
short, shortest, current가 업데이트 된 이후에 발생할 것으로 생각되었으나, 재현되지 않음.
shortest를 current에 merge할때 문제가 있을꺼라 생각되어, 재현하기 위해서 getKmaStnHourlyWeather 빼고 시도했지만 재현되지 않았음.

**Comment by kimalec** [comment]
56분부터 4분정도만 발생했으며, tw-wzdfac에서는 발생하지 않았음.
두 코드는 차이는 yesterday에 관한 오류 수정만 있음. #1027

**Comment by kimalec** [comment]
어제 발생하지 않았음. 좀 더 지켜보고, 문제 재현이 없으면 닫도록 하겠습니다.
