### ISSUE TITLE
TransactionTooLargeException

### ISSUE THREAD

**Issue by skywlrl** [WizardFactory/TodayWeather#1175]
비정상 종료 및 예외
0.9.10버전에서 4건 발생
0.9.12 버전에서 17건 발생
- TransactionTooLargeException (@BinderProxy:transact:-2) {main}
- https://developer.android.com/reference/android/os/TransactionTooLargeException.html

**Comment by kimalec** [comment]
```java
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=8; index=8
	at net.wizardfactory.todayweather.widget.JsonElement.WeatherElement.makeWidgetData(WeatherElement.java:238)
	at net.wizardfactory.todayweather.widget.WidgetUpdateService.updateWidget(WidgetUpdateService.java:302)
	at net.wizardfactory.todayweather.widget.WidgetUpdateService.findAddressAndWeatherUpdate(WidgetUpdateService.java:210)
	at net.wizardfactory.todayweather.widget.WidgetUpdateService.registerLocationUpdates(WidgetUpdateService.java:147)
	at net.wizardfactory.todayweather.widget.WidgetUpdateService.startUpdate(WidgetUpdateService.java:105)
	at net.wizardfactory.todayweather.widget.WidgetUpdateService.onStartCommand(WidgetUpdateService.java:69)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2991)
```
https://play.google.com/apps/publish/?dev_acc=00534617298003426325#ErrorClusterDetailsPlace:p=net.wizardfactory.todayweather&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.ArrayIndexOutOfBoundsException&tf=WeatherElement.java&tc=net.wizardfactory.todayweather.widget.JsonElement.WeatherElement&tm=makeWidgetData&nid&an&c&s=new_status_desc&ed=1475902821738

**Comment by kimalec** [comment]
http://mydevspace.blogspot.kr/2015/06/androidostransactiontoolargeexception.html android.os.TransactionTooLargeException 에러

**Comment by kimalec** [comment]
발생하지 않음.
