### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1193]
``` java
java.lang.NoSuchMethodError: org.json.JSONObject.wrap
    at io.airbridge.cordova.AirBridgePlugin$1.onLink(AirBridgePlugin.java:57)
    at io.airbridge.LinkHandler._handleSimpleLinkUri(LinkHandler.java:88)
    at io.airbridge.LinkHandler.handleSimpleLink(LinkHandler.java:96)
    at io.airbridge.DeferredChecker$1.done(DeferredChecker.java:58)
    at io.airbridge.networking.ABRequest$1.onPostExecute(ABRequest.java:73)
    at io.airbridge.networking.ABRequest$1.onPostExecute(ABRequest.java:45)
    at android.os.AsyncTask.finish(AsyncTask.java:631)
    at android.os.AsyncTask.access$600(AsyncTask.java:177)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:176)
    at android.app.ActivityThread.main(ActivityThread.java:5319)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
    at dalvik.system.NativeStart.main(Native Method)
```

어제, 오후 10:26
0.9.14
Galaxy Win(deloslteskt)
왜않대요
어제, 오후 9:33
0.9.14
IM-A830K(ef45k)
계속 앱에서 나가져요.

https://play.google.com/apps/publish/?dev_acc=00534617298003426325#ErrorClusterDetailsPlace:p=net.wizardfactory.todayweather&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.NoSuchMethodError&tf=AirBridgePlugin.java&tc=io.airbridge.cordova.AirBridgePlugin$1&tm=onLink&nid&an&c&s=new_status_desc&ed=1476537993407

**Comment by skywlrl** [comment]
예외 설명 / 안드로이드 버전 / 비정상 종료 횟수
NoSuchMethodError (@AirBridgePlugin$1:onLink:57) {main}	/ 4.1.2	/ 27
NoSuchMethodError (@AirBridgePlugin$1:onLink:57) {main}	/ 4.3		/ 7
NoSuchMethodError (@AirBridgePlugin$1:onLink:57) {main}	/ 4.2.2	/ 5
NoSuchMethodError (@AirBridgePlugin$1:onLink:57) {main}	/ 4.0.3	/ 1
NoSuchMethodError (@AirBridgePlugin$1:onLink:57) {main}	/ 4.0.4	/ 1

=> 4.4 미만 버전에서 문제가 발생함. crosswalk에서 지원 안되는 것인지 확인 필요할 듯

**Comment by kimalec** [comment]
JSONObject 라는 기본 제공 Class에서 사용하는 wrap 메소드가 
API Level 19 (킷캣) 이상부터 사용가능한 메소드여서 생기는 문제였습니다.

저희쪽에서 릴리즈시 모든 테스트를 거치고 릴리즈 하였으나,
테스트하는 프로젝트의 minSdkVersion 이 20 이상이어서 문제없이 릴리즈 된것으로 파악되었습니다.

현재는 킷캣 버전 확인후 메소드를 사용하도록 수정하였습니다.

**Comment by kimalec** [comment]
설명으로는 100프로 재현같은데, 버전 테스트할때 발견안된게 이상하네요 ㅋ
깔린 버전 해보니, 바로 죽긴하지만 버전에 업데이트 되어 있는걸보아 테스트는 해본거 같은데 이상하군요.

**Comment by kimalec** [comment]
0.9.14에서 plugin만 업데이트해서 hot fix release 하였음.
