### ISSUE TITLE
어제부터 정보 읽어오는 도중 멈추네요 ㅠ ㅠ v0.9.17

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1246]
휴대기기 LG G3 Cat.6(tiger6)
OS Android 4.4

**Comment by kimalec** [comment]
store에 올라간 버전으로 문제 확인했슴.

S7, 6P, Mi5, S4, G3에서는 정상동작확인되고, G3 Cat.6에서 오동작함.

**Comment by kimalec** [comment]
service.twads.js:207 에서 아래와 같은 에러가 발생하긴하지만, 릴리즈 아닌 상태에서는 정상동작함.
```
Uncaught TypeError: Converting circular structure to JSON 
```

**Comment by kimalec** [comment]
새로 빌드하는 경우 재현되지 않음. - 빌드 자동화시 개선 필요

**Comment by kimalec** [comment]
아래의 에러로 발생하는 문제임.
```
11-03 11:59:05.854 27409-27409/net.wizardfactory.todayweather I/chromium: [INFO:CONSOLE(150)] "TypeError: string is not a function
                                                                              at nativeExec (file:///android_asset/www/plugins/cordova-plugin-app-preferences/www/apppreferences.js:176:11)
                                                                              at AppPreferences.store (file:///android_asset/www/plugins/cordova-plugin-app-preferences/www/apppreferences.js:188:3)
                                                                              at file:///android_asset/www/js/services.js:272:28
                                                                              at file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:470:7438
                                                                              at Object.n.Platform.ready (file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:22:28277)
                                                                              at Object.n.ready (file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js:470:7341)
                                                                              at Object.obj._saveCitiesPreference (file:///android_asset/www/js/services.js:265:28)
                                                                              at Object.obj.saveCities (file:///android_asset/www/js/services.js:310:18)
                                                                              at Object.obj.disableCity (file:///android_asset/www/js/services.js:176:18)
                                                                              at file:///android_asset/www/js/controllers.js:1645:33", source: file:///android_asset/www/lib/ionic/js/ionic.bundle.min.js (150)
```

**Comment by kimalec** [comment]
#1161 에서 최신 버전 적용해야 정상 동작함.

**Comment by kimalec** [comment]
plugin add되면서 뭔가 잘 못 된것으로 보임.
cordova-plugin-app-preferences 삭제하고, 다시 추가한 후 build하면 정상 동작함.

**Comment by kimalec** [comment]
스트립트상으로 해결안되고, android stuio에서 gradle생성하거나, 그런것과 관련이 있어 보임.

**Comment by kimalec** [comment]
API를 README와 다르게 사용했었음.

아래 참고하여 수정.
https://github.com/apla/me.apla.cordova.app-preferences/tree/version/0.7.7
