### ISSUE TITLE
push notification에서 단위, 다국어, 세계날씨 지원.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1308]
#418 
push notification 업데이트시에 단위, 다국어 지원하게 개선.

**Comment by kimalec** [comment]
#1209 #613 #635

**Comment by kimalec** [comment]
알람기준 시간이 애매함. 각 지역에 로컬 타임 기준으로 할 것인가? 핸드폰의 시간을 기준으로 할 것인가?

**Comment by kimalec** [comment]
push의 경우 daily api에서 받은 문장을 그대로 전달하기 때문에 service api (makeDailySummary)에서 제공해야 함.
Accept-Language 를 사용해서 적용할 예정임.

**Comment by kimalec** [comment]
https://github.com/mashpie/i18n-node

**Comment by kimalec** [comment]
- [ ] (대기)미세먼지예보, 강수확률 빠졌음.
- [ ] Cannot read property '1' of undefined
```
TypeError: Cannot read property '1' of undefined
    at ControllerPush._makeDsfPushMessage (/home/todayweather/push-tw/server/controllers/controllerPush.js:443:44)
    at Request._callback (/home/todayweather/push-tw/server/controllers/controllerPush.js:618:34)
```
- [ ] Cannot set property 'locale' of undefined
```
/home/todayweather/push-tw/server/node_modules/i18n/i18n.js:408
    targetObject.locale = locales[targetLocale] ? targetLocale : defaultLocale;
                        ^
TypeError: Cannot set property 'locale' of undefined
    at Object.i18nSetLocale [as setLocale] (/home/todayweather/push-tw/server/node_modules/i18n/i18n.js:408:25)
    at ControllerPush._makeKmaPushMessage (/home/todayweather/push-tw/server/controllers/controllerPush.js:193:10)
```

**Comment by kimalec** [comment]
검토한 코드 diff 
```diff
diff --git a/server/controllers/controllerPush.js b/server/controllers/controllerPush.js
index f0dfb17..8208354 100644
--- a/server/controllers/controllerPush.js
+++ b/server/controllers/controllerPush.js
@@ -190,7 +190,9 @@ ControllerPush.prototype.sendIOSNotification = function (pushInfo, notification,
 ControllerPush.prototype._makeKmaPushMessage = function (pushInfo, dailyInfo) {
     var pushMsg;
 
+if (pushInfo.lang) {
     i18n.setLocale(pushInfo.lang);
+}
 
     var location = "";
     if (pushInfo.name) {
@@ -231,12 +233,14 @@ ControllerPush.prototype._makeKmaPushMessage = function (pushInfo, dailyInfo) {
     }
 
     if (theDay.taMin != undefined && theDay.taMax != undefined) {
+if (pushInfo.units) {
         theDay.taMin = unitConverter.convertUnits(dailyInfo.units.temperatureUnit, pushInfo.units.temperatureUnit, theDay.taMin);
         theDay.taMax = unitConverter.convertUnits(dailyInfo.units.temperatureUnit, pushInfo.units.temperatureUnit, theDay.taMax);
         if (pushInfo.units.temperatureUnit == "F") {
             theDay.taMin = Math.round(theDay.taMin);
             theDay.taMax = Math.round(theDay.taMax);
         }
+}
 
         dailyArray.push(theDay.taMin+"˚/"+theDay.taMax+"˚");
     }
@@ -276,10 +280,12 @@ ControllerPush.prototype._makeKmaPushMessage = function (pushInfo, dailyInfo) {
         hourlyArray.push(weather);
     }
     if (current.t1h) {
+if (pushInfo.units) {
         current.t1h = unitConverter.convertUnits(dailyInfo.units.temperatureUnit, pushInfo.units.temperatureUnit, current.t1h);
         if (pushInfo.units.temperatureUnit == "F") {
             current.t1h = Math.round(current.t1h);
         }
+}
         var str = current.t1h+"˚";
         hourlyArray.push(str);
     }
@@ -289,8 +295,10 @@ ControllerPush.prototype._makeKmaPushMessage = function (pushInfo, dailyInfo) {
     }
     if (current.pty && current.pty > 0 && current.rn1 != undefined) {
         current.ptyStr = cTown._convertKmaPtyToStr(current.pty);
+if (pushInfo.units) {
         current.rn1 = unitConverter.convertUnits(dailyInfo.units.precipitationUnit, pushInfo.units.precipitationUnit, current.rn1);
         hourlyArray.push(current.ptyStr+" "+ current.rn1 + pushInfo.units.precipitationUnit);
+}
     }
     hourlySummary += hourlyArray.toString();
     //불쾌지수
@@ -314,6 +322,9 @@ ControllerPush.prototype._requestKmaDailySummary = function (pushInfo, callback)
         url += '/' + encodeURIComponent(town.third);
     }
 
+if (pushInfo.lang == undefined) {
+pushInfo.lang = "ko";
+}
     log.info('request url='+url);
     var options = {
         url : url,
@@ -431,7 +442,12 @@ ControllerPush.prototype._makeDsfPushMessage = function(pushInfo, worldWeatherDa
     var self = this;
     var pushMsg;
 
+if (pushInfo.lang) {
     i18n.setLocale(pushInfo.lang);
+}
+else {
+    i18n.setLocale("ko");
+}
 
     var location = "";
     if (pushInfo.name) {
@@ -494,6 +510,7 @@ ControllerPush.prototype._makeDsfPushMessage = function(pushInfo, worldWeatherDa
         dailyArray.push(cTown._getWeatherEmoji(theDay.skyIcon));
     }
 
+       if (pushInfo.units) {
     if (pushInfo.units.temperatureUnit == 'C') {
         theDay.taMin = theDay.tempMin_c;
         theDay.taMax = theDay.tempMax_c;
@@ -502,6 +519,7 @@ ControllerPush.prototype._makeDsfPushMessage = function(pushInfo, worldWeatherDa
         theDay.taMin = Math.round(theDay.tempMin_f);
         theDay.taMax = Math.round(theDay.tempMax_f);
     }
+}
 
     if (!(theDay.taMin == undefined) && !(theDay.taMax == undefined)) {
         dailyArray.push(theDay.taMin+"˚/"+theDay.taMax+"˚");
@@ -548,7 +566,7 @@ ControllerPush.prototype._makeDsfPushMessage = function(pushInfo, worldWeatherDa
 
     var str;
     if ( !(current.temp_c == undefined) && !(current.temp_f == undefined) ) {
-        if (pushInfo.units.temperatureUnit == 'C') {
+        if (pushInfo.units && pushInfo.units.temperatureUnit == 'C') {
             str = current.temp_c+"˚";
         }
         else {
```
