### ISSUE TITLE
 areaNo가 없는 DB 보정(error to get health index)

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1509]
강원도/속초시/설악동

```js
TypeError: Cannot read property 'length' of undefined
at /var/app/current/controllers/controllerTown.js:1914:39
at Array.forEach (native)
at /var/app/current/controllers/controllerTown.js:1912:35
at /var/app/current/node_modules/mongoose/lib/query.js:2316:9
at newTickHandler (/var/app/current/node_modules/mpromise/lib/promise.js:234:18)
at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)
```

**Comment by kimalec** [comment]
240개의 areaNo가 없는 DB 보정해야함.

**Comment by kimalec** [comment]
아래와 같이 안 맞는 경우 다수 존재
```
error Fail to find area no=4119555000 {"method":"getHealthDay","region":"경기도","city":"부천시원미구","town":"원미2동"}
```

보건지수나, 생활지수에 첨부된 가장 최근의 데이터를 사용해야함.
[20160704_AreaNo.zip](https://github.com/WizardFactory/TodayWeather/files/888381/20160704_AreaNo.zip)
