### ISSUE TITLE
NoSuchMethodError No static method getNoBackupFilesDir

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1552]
```
java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzw; or its super classes (declaration of 'com.google.android.gms.common.util.zzw' appears in /data/app/net.wizardfactory.todayweather-1/base.apk)
	at com.google.android.gms.iid.zzd.zzkq(Unknown Source)
	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
	at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
	at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by kimalec** [comment]
push 등록하면 죽음.
push 등록되어 있으면 앱 실행하자마자 죽음.

**Comment by kimalec** [comment]
#1420 에서 버전 고정했음.

**Comment by kimalec** [comment]
https://github.com/phonegap/phonegap-plugin-push/issues/1591

**Comment by kimalec** [comment]
Version 1.9.0 (and above) of this plugin supports CocoaPods installation of the Google Cloud Messaging library.
https://cocoapods.org

**Comment by kimalec** [comment]
http://stackoverflow.com/questions/42304714/ionic-cordova-project-not-compiling-when-using-phonegap-push-plugin
