### ISSUE TITLE
[Android] NoSuchMethodError at _bundleToJson(IonicDeeplink.java:139)

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1553]
```
java.lang.NoSuchMethodError: org.json.JSONObject.wrap
 at io.ionic.links.IonicDeeplink._bundleToJson(IonicDeeplink.java:139)
 at io.ionic.links.IonicDeeplink.handleIntent(IonicDeeplink.java:68)
 at io.ionic.links.IonicDeeplink.initialize(IonicDeeplink.java:54)
 at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
   at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:172)
   at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:98)
 at org.apache.cordova.PluginManager.init(PluginManager.java:87)
  at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:116)
     at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:144)
 at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:214)
  at net.wizardfactory.todayweather.MainActivity.onCreate(MainActivity.java:32)
  at android.app.Activity.performCreate(Activity.java:4668)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1939)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2000)
   at android.app.ActivityThread.access$600(ActivityThread.java:123)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
 at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:137)
     at android.app.ActivityThread.main(ActivityThread.java:4443)
 at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:511)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
  at dalvik.system.NativeStart.main(Native Method)
```

**Comment by kimalec** [comment]
https://github.com/phonegap/phonegap-plugin-push/issues/1601

**Comment by kimalec** [comment]
이슈 발생시 재검토
