### ISSUE TITLE
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1566]
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error
   at model.wrappedPointCut [as save] (/home/ec2-user/TodayWeather/server/node_modules/mongoose/lib/document.js:1891:27)
   at /home/ec2-user/TodayWeather/server/lib/kmaScraper.js:596:22
   at model.Query.<anonymous> (/home/ec2-user/TodayWeather/server/node_modules/mongoose/lib/model.js:3361:16)
   at /home/ec2-user/TodayWeather/server/node_modules/kareem/index.js:259:21
   at /home/ec2-user/TodayWeather/server/node_modules/kareem/index.js:127:16
   at _combinedTickCallback (internal/process/next_tick.js:73:7)
   at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:128:9)
```

**Comment by kimalec** [comment]
https://github.com/Automattic/mongoose/issues/4135

**Comment by kimalec** [comment]
Fixed from #1548
