### ISSUE TITLE
[kma][health] error: Cast to number failed for value "*" at path "index"in insert DB(healthData)

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1575]
error 
```
1|www      | error:  CastError: Cast to number failed for value "*" at path "index"
1|www      |     at MongooseError.CastError (/home/todayweather/TodayWeather/server/node_modules/mongoose/lib/error/cast.js:19:11)
1|www      |     at SchemaNumber.cast (/home/todayweather/TodayWeather/server/node_modules/mongoose/lib/schema/number.js:231:9)
1|www      |     at SchemaNumber.castForQuery (/home/todayweather/TodayWeather/server/node_modules/mongoose/lib/schema/number.js:282:14)
1|www      |     at Query._castUpdateVal (/home/todayweather/TodayWeather/server/node_modules/mongoose/lib/query.js:2492:17)
1|www      |     at Query._walkUpdatePath (/home/todayweather/TodayWeather/server/node_modules/mongoose/lib/query.js:2439:25)
1|www      |     at Query._castUpdate (/home/todayweather/TodayWeather/server/node_modules/mongoose/lib/query.js:2311:23)
1|www      |     at Query.update (/home/todayweather/TodayWeather/server/node_modules/mongoose/lib/query.js:2106:22)
1|www      |     at Function.update (/home/todayweather/TodayWeather/server/node_modules/mongoose/lib/model.js:2054:13)
1|www      |     at /home/todayweather/TodayWeather/server/controllers/controllerHealthDay.js:161:28
1|www      |     at /home/todayweather/TodayWeather/server/node_modules/async/lib/async.js:356:13
1|www      |     at iterate (/home/todayweather/TodayWeather/server/node_modules/async/lib/async.js:262:13)
1|www      |     at /home/todayweather/TodayWeather/server/node_modules/async/lib/async.js:274:29
1|www      |     at /home/todayweather/TodayWeather/server/node_modules/async/lib/async.js:44:16
1|www      |     at /home/todayweather/TodayWeather/server/node_modules/async/lib/async.js:358:17
1|www      |     at /home/todayweather/TodayWeather/server/controllers/controllerHealthDay.js:168:21
1|www      |     at /home/todayweather/TodayWeather/server/node_modules/mongoose/lib/model.js:3361:16
```

rest api 결과
```
{"code":"D01","areaNo":"4200000000","date":"2017050806","today":"*","tomorrow":"*","theDayAfterTomorrow":"*"}
```

#1466

**Comment by kimalec** [comment]
#1466 동일 이슈
