### ISSUE TITLE
[iOS][widget] ios build 개발환경 setup

### ISSUE THREAD

**Issue by seankim2** [WizardFactory/TodayWeather#1592]
ios build 개발환경을 setup하고 error fix내용을 기술하여, 추후 동일한 에러가 나올시 쉽게 처리하도록 한다.

**Comment by seankim2** [comment]
* ionic state reset
```
You cannot run any state commands on a project that is not an Ionic project.
Try adding an ionic.project file or running ionic start to get an application to save or restore (CLI v1.7.14)

Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.3.2
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.2.0
Xcode version: Xcode 8.2.1 Build version 8C1002 
```
* Ionic serve 명령이후 ionic.proect 파일이 생성되고, ionic state 명령 사용 가능

**Comment by seankim2** [comment]
* Ionic build ios
```
 ✗ (node:12570) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Running command: /Users/mis2010/workjs/TodayWeather/TodayWeather/client/hooks/after_prepare/010_add_platform_class.js /Users/mis2010/workjs/TodayWeather/TodayWeather/client
add to body class: platform-ios
Running command: /Users/mis2010/workjs/TodayWeather/TodayWeather/client/hooks/after_prepare/011_update_config.js /Users/mis2010/workjs/TodayWeather/TodayWeather/client
net.js:647
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not object
    at Socket.write (net.js:647:11)
    at /Users/mis2010/workjs/TodayWeather/TodayWeather/client/hooks/after_prepare/011_update_config.js:296:24
    at Function.forEach (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/node_modules/lodash/dist/lodash.js:2331:13)
    at /Users/mis2010/workjs/TodayWeather/TodayWeather/client/hooks/after_prepare/011_update_config.js:291:7
    at Object.<anonymous> (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/hooks/after_prepare/011_update_config.js:300:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
Error: Hook failed with error code 1: /Users/mis2010/workjs/TodayWeather/TodayWeather/client/hooks/after_prepare/011_update_config.js
```
* https://github.com/fechanique/cordova-plugin-fcm/issues/213
  * android home과 연관성이 의심되어 기존에 지웠던 ionic android platform을 추가
  * 아래 에러 발생
```
KwangHo-Kim-ui-MacBook-Pro:client mis2010$ ionic platform add android
 ✗ (node:12404) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Updated the hooks directory to have execute permissions
Adding android project...
Creating Cordova project for the Android platform:
Path: platforms/android
Package: net.wizardfactory.todayweather
Name: TodayWeather
Activity: MainActivity
Android target: android-24
Subproject Path: CordovaLib
Android project created with cordova-android@6.0.0
Installing "cordova-admob" for android
Failed to install 'cordova-admob':CordovaError: Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.
    at /Users/mis2010/workjs/TodayWeather/TodayWeather_remote/TodayWeather/client/platforms/android/cordova/lib/check_reqs.js:222:19
    at _fulfilled (/Users/mis2010/workjs/TodayWeather/TodayWeather_remote/TodayWeather/client/platforms/android/cordova/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/mis2010/workjs/TodayWeather/TodayWeather_remote/TodayWeather/client/platforms/android/cordova/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/mis2010/workjs/TodayWeather/TodayWeather_remote/TodayWeather/client/platforms/android/cordova/node_modules/q/q.js:796:13)
    at /Users/mis2010/workjs/TodayWeather/TodayWeather_remote/TodayWeather/client/platforms/android/cordova/node_modules/q/q.js:857:14
    at runSingle (/Users/mis2010/workjs/TodayWeather/TodayWeather_remote/TodayWeather/client/platforms/android/cordova/node_modules/q/q.js:137:13)
    at flush (/Users/mis2010/workjs/TodayWeather/TodayWeather_remote/TodayWeather/client/platforms/android/cordova/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.
```

**Comment by seankim2** [comment]
* Android Studio 설치 및 path export
```
export ANDROID_HOME=/<installation location>/android-sdk-macosx
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
```
* ionic platform add android
```
KwangHo-Kim-ui-MacBook-Pro:client mis2010$ ionic platform add android
 ✗ (node:2668) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Updated the hooks directory to have execute permissions
Adding android project...
Creating Cordova project for the Android platform:
Path: platforms/android
Package: net.wizardfactory.todayweather
Name: TodayWeather
Activity: MainActivity
Android target: android-24
Subproject Path: CordovaLib
Android project created with cordova-android@6.0.0
Installing "cordova-admob" for android
ANDROID_HOME=/Users/mis2010/Desktop/Development/Android/android-sdk-macosx
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home
Failed to install 'cordova-admob':CordovaError: Requirements check failed for JDK 1.8 or greater
    at /Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/android/cordova/lib/check_reqs.js:278:19
    at _fulfilled (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/android/cordova/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/android/cordova/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/android/cordova/node_modules/q/q.js:796:13)
    at /Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/android/cordova/node_modules/q/q.js:604:44
    at runSingle (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/android/cordova/node_modules/q/q.js:137:13)
    at flush (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/android/cordova/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Requirements check failed for JDK 1.8 or greater
```
* Mac OSX, XCode, 자바 업그레이드가 필요함
  * Osx 10.12.4 (mac sierra 로 변경)
  * Xcode 8.3.2로 업그레이드
  * Jdk 1.7->1.8 업그레이드
    * http://recipes4dev.tistory.com/52

**Comment by seankim2** [comment]
* ionic state reset
```
wangHo-Kim-ui-MacBook-Pro:client mis2010$ ionic state reset
Removed platforms and plugins
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add ios
cordova platform add android

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-device

/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:543
        throw 'Error executing "' + pluginCommand + '":\n' + output;
        ^
Error executing "cordova plugin add cordova-plugin-device":
Fetching plugin "cordova-plugin-device" via npm
Installing "cordova-plugin-device" for android
ANDROID_HOME=/Users/mis2010/Desktop/Development/Android/android-sdk-macosx
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
Failed to install 'cordova-plugin-device':CordovaError: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
Looked here: /Users/mis2010/Desktop/Development/Android/android-sdk-macosx/tools/templates/gradle/wrapper
    at Object.module.exports.check_gradle (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/android/cordova/lib/check_reqs.js:90:25)
    at GradleBuilder.prepEnv (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/android/cordova/lib/builders/GradleBuilder.js:161:23)
    at Api.module.exports.runClean (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/android/cordova/lib/build.js:131:20)
    at /Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/android/cordova/Api.js:391:50
```

**Comment by seankim2** [comment]
* @kimalec 현재 사용하고 있는 jdk version 은 무엇인가요?

**Comment by seankim2** [comment]
* npm install 시 아래 에러가 발생시 rm -rf node_modules/* 로 해결
```
KwangHoKimuiMBP:client mis2010$ npm install
TodayWeather@0.9.45 /Users/mis2010/workjs/TodayWeather/TodayWeather/client
├─┬ gulp-delete-lines@0.0.7 
│ └─┬ event-stream@3.1.7 
│   ├── duplexer@0.1.1 
│   ├── from@0.1.7 
│   ├── map-stream@0.1.0 
│   ├── pause-stream@0.0.11 
│   ├── split@0.2.10 
│   └── stream-combiner@0.0.4 
└── UNMET PEER DEPENDENCY lodash@4.17.4 extraneous

npm WARN cordova-config-utils@1.0.3 requires a peer of lodash@^3.10.1 but none was installed.
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! path /Users/mis2010/workjs/TodayWeather/TodayWeather/client/node_modules/.xml2js.DELETE/node_modules/lodash
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rename

npm ERR! Error: EACCES: permission denied, rename '/Users/mis2010/workjs/TodayWeather/TodayWeather/client/node_modules/.xml2js.DELETE/node_modules/lodash' -> '/Users/mis2010/workjs/TodayWeather/TodayWeather/client/node_modules/xml2js/node_modules/lodash'
npm ERR!     at /usr/local/lib/node_modules/npm/lib/install/action/finalize.js:64:7
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR!     at Array.forEach (native)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR!     at Array.forEach (native)
npm ERR!     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR!     at moveModules (/usr/local/lib/node_modules/npm/lib/install/action/finalize.js:61:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/install/action/finalize.js:56:70
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:30:20
npm ERR!     at FSReqWrap.oncomplete (fs.js:117:15)
npm ERR! 
npm ERR! Error: EACCES: permission denied, rename '/Users/mis2010/workjs/TodayWeather/TodayWeather/client/node_modules/.xml2js.DELETE/node_modules/lodash' -> '/Users/mis2010/workjs/TodayWeather/TodayWeather/client/node_modules/xml2js/node_modules/lodash'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, rename '/Users/mis2010/workjs/TodayWeather/TodayWeather/client/node_modules/.xml2js.DELETE/node_modules/lodash' -> '/Users/mis2010/workjs/TodayWeather/TodayWeather/client/node_modules/xml2js/node_modules/lodash'
npm ERR!     at /usr/local/lib/node_modules/npm/lib/install/action/finalize.js:64:7
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR!     at Array.forEach (native)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR!     at Array.forEach (native)
npm ERR!     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR!     at moveModules (/usr/local/lib/node_modules/npm/lib/install/action/finalize.js:61:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/install/action/finalize.js:56:70
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:30:20
npm ERR!     at FSReqWrap.oncomplete (fs.js:117:15)
npm ERR! 
npm ERR! Error: EACCES: permission denied, rename '/Users/mis2010/workjs/TodayWeather/TodayWeather/client/node_modules/.xml2js.DELETE/node_modules/lodash' -> '/Users/mis2010/workjs/TodayWeather/TodayWeather/client/node_modules/xml2js/node_modules/lodash'
npm ERR!     at Error (native) parent: 'TodayWeather' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mis2010/workjs/TodayWeather/TodayWeather/client/npm-debug.log
```

**Comment by seankim2** [comment]
* cannot find plugin.xml for plugin "ionic-plugin-deeplinks" 이슈
```
------------------------------------
Ionic CLI is out of date:
 * Locally installed version: 1.7.14
 * Latest version: 3.1.2
 * https://github.com/driftyco/ionic-cli/blob/master/CHANGELOG.md
 * Run npm install -g ionic to update
------------------------------------


/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:543
        throw 'Error executing "' + pluginCommand + '":\n' + output;
        ^
Error executing "cordova plugin add ionic-plugin-deeplinks --variable URL_SCHEME="todayweather" --variable DEEPLINK_SCHEME="http" --variable DEEPLINK_HOST="net.wizardfactory.todayweather" --variable ANDROID_PATH_PREFIX="/" ":
Error: Cannot find plugin.xml for plugin "ionic-plugin-deeplinks". Please try adding it again.

[11:40:52] 'build_ios' errored after 3.47 min
[11:40:52] Error: Command `ionic state reset` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```
* package.json에서 ionic-plugin-deeplinks 부분 삭제

**Comment by seankim2** [comment]
* package.json 에서 fabric, push, android platform 삭제
* npm uninstall cordova-config-utils 실행 해도 아래 에러 발생됨...
```
Updating hooks directory to have execution permissions...
bower                     invalid-meta for:/Users/mis2010/workjs/TodayWeather/TodayWeather/client/bower.json
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
[23:51:49] Using gulpfile ~/workjs/TodayWeather/TodayWeather/client/gulpfile.js
[23:51:49] Starting 'sass'...
[23:51:51] Finished 'sass' after 1.7 s
 ✗ (node:48519) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Running command: /Users/mis2010/workjs/TodayWeather/TodayWeather/client/hooks/after_prepare/011_update_config.js /Users/mis2010/workjs/TodayWeather/TodayWeather/client
net.js:647
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not object
    at Socket.write (net.js:647:11)
    at /Users/mis2010/workjs/TodayWeather/TodayWeather/client/hooks/after_prepare/011_update_config.js:296:24
    at Function.forEach (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/node_modules/lodash/dist/lodash.js:2331:13)
    at /Users/mis2010/workjs/TodayWeather/TodayWeather/client/hooks/after_prepare/011_update_config.js:291:7
    at Object.<anonymous> (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/hooks/after_prepare/011_update_config.js:300:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
Error: Hook failed with error code 1: /Users/mis2010/workjs/TodayWeather/TodayWeather/client/hooks/after_prepare/011_update_config.js
[23:52:00] Finished 'build_ios' after 6.78 min
```

**Comment by seankim2** [comment]
* 위 에러 난 상태에서 아래 command실행 후 정상적으로 빌드됨
```
# npm uninstall cordova-config-utils 
# cd node_modules/cordova-uglify/;npm install
# bower install
# gulp sass
# ionic build ios
```
