### ISSUE TITLE
Error: connect ETIMEDOUT 210.99.81.18:80

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1601]
```
1|www      | error:  Error: connect ETIMEDOUT 210.99.81.18:80
1|www      |     at Object.exports._errnoException (util.js:1022:11)
1|www      |     at exports._exceptionWithHostPort (util.js:1045:20)
1|www      |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```

**Comment by kimalec** [comment]
주소가 openapi.airkorea.or.kr 임 확인 필요함.

**Comment by kimalec** [comment]
동시요청 갯수 제한에 걸리는 듯하며, 못 가지고 온 지역이 있는 경우 재시도하게 수정 필요.
