### ISSUE TITLE
[0.9.46] Crash 이슈

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1605]
```
java.lang.NullPointerException: 
  at com.alexdisler.inapppurchases.IabHelper.queryPurchases(IabHelper.java:849)
```

```
Caused by: java.lang.NullPointerException: 
  at net.wizardfactory.todayweather.widget.WidgetUpdateService.onStartCommand(WidgetUpdateService.java:71)
```

```
java.lang.IllegalStateException: 
  at android.preference.ListPreference.onPrepareDialogBuilder(ListPreference.java:248)
  at android.preference.DialogPreference.showDialog(DialogPreference.java:315)
  at android.preference.DialogPreference.onClick(DialogPreference.java:276)
  at android.preference.Preference.performClick(Preference.java:1013)
  at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:221)
```

```
java.lang.NullPointerException: 
  at android.app.LoadedApk.getAssets(LoadedApk.java:581)
  at android.app.LoadedApk.prepareResources(LoadedApk.java:643)
  at android.app.LoadedApk.makeApplication(LoadedApk.java:636)
```

```
Caused by: java.lang.IllegalArgumentException: 
  at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:940)
  at android.app.ContextImpl.unbindService(ContextImpl.java:1983)
  at android.content.ContextWrapper.unbindService(ContextWrapper.java:541)
  at com.alexdisler.inapppurchases.IabHelper.dispose(IabHelper.java:301)
```

```
Caused by: java.lang.IllegalStateException: 
  at android.app.LoadedApk.initializeJavaContextClassLoader(LoadedApk.java:429)
  at android.app.LoadedApk.makeApplication(LoadedApk.java:577)
```

```
android.view.WindowManager$BadTokenException: 
  at android.view.ViewRootImpl.setView(ViewRootImpl.java:687)
  at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:288)
  at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
  at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3502)
```

**Comment by kimalec** [comment]
*Fix widget.WidgetUpdateService.onStartCommand(WidgetUpdateService.java:71)*
https://github.com/WizardFactory/cordova-plugin-todayweather-android-widget/commit/a9c4af92155504bc829c7b207e3113de0118cab6

**Comment by kimalec** [comment]
java.lang.IllegalStateException
  https://stackoverflow.com/questions/23050150/create-listpreferences-in-android
  https://developer.android.com/reference/java/lang/IllegalStateException.html
  http://sjava.net/2014/12/listview에서-java-lang-illegalstateexception-에러-처리/

**Comment by kimalec** [comment]
이슈 개별 오픈해서 진행하고 본 이슈 close함
