### ISSUE TITLE
[WW] AQI 인터페이스 lib

### ISSUE THREAD

**Issue by pokers** [WizardFactory/TodayWeather#1632]
AQI 데이터 가져오는 API 생성

http://aqicn.org/json-api/doc/

**Comment by kimalec** [comment]
config.js도 PR해주세요.
```
TypeError: Cannot read property 'key' of undefined
at controllerAqi.requestAqiData (/var/app/current/controllers/worldWeather/controllerAqi.js:176:32)
at /var/app/current/controllers/worldWeather/controllerRequester.js:591:30
```

**Comment by kimalec** [comment]
- [ ] api.waqi.info error 나는 경우 죽지 않게 예외처리필요.
- [ ] iaqi에 있는 값도 전달

```
"iaqi": {
            "co": {
                "v": 2.3
            },
            "h": {
                "v": 53
            },
            "no2": {
                "v": 16.7
            },
            "o3": {
                "v": 6.4
            },
            "p": {
                "v": 1028
            },
            "pm10": {
                "v": 10
            },
            "pm25": {
                "v": 18
            },
            "so2": {
                "v": 1.5
            },
            "t": {
                "v": 11.15
            }
        },
        "time": {
            "s": "2017-07-01 00:00:00",
            "tz": "+09:00",
            "v": 1498867200
        }
```
국내날씨에서 제공하는 값
```
"arpltn": {
    "stationName": "중구",
    "pm10Grade": 2,
    "no2Grade": 1,
    "o3Grade": 2,
    "coGrade": 1,
    "so2Grade": 1,
    "khaiGrade": 2,
    "khaiValue": 71,
    "pm10Value": 36,
    "no2Value": 0.028,
    "o3Value": 0.036,
    "coValue": 0.4,
    "so2Value": 0.002,
    "dataTime": "2017-06-30 23:00",
    "pm25Grade": 2,
    "pm25Value": 29,
    "pm10Str": "보통",
    "pm25Str": "보통",
    "o3Str": "보통",
    "no2Str": "좋음",
    "coStr": "좋음",
    "so2Str": "좋음",
    "khaiStr": "보통"
}
```

**Comment by pokers** [comment]
@kimalec : "api.waqi.info error 나는 경우 죽지 않게 예외처리필요. " 이게 언제 나오는 상황이지?
왠만한 error 처리는 다 했다고 생각했는데

**Comment by kimalec** [comment]
waqi와 darksky를 동시에 호출해서 시간 감소가 필요함.
<img width="630" alt="2017-07-03 04 42 38" src="https://user-images.githubusercontent.com/6895272/27773018-60c4d670-5faa-11e7-98e3-317ef1414c87.png">

**Comment by kimalec** [comment]
local 에서 에러 수정한 사항
```diff
diff --git a/server/controllers/worldWeather/controllerAqi.js b/server/controllers/worldWeather/controllerAqi.js
index 59aa568..9617e47 100644
--- a/server/controllers/worldWeather/controllerAqi.js
+++ b/server/controllers/worldWeather/controllerAqi.js
@@ -211,7 +211,7 @@ controllerAqi.prototype.requestAqiData = function(geocode, From, To, timeOffset,
                 requester.getAqiData(geocode, key, function(err, result){
                     if(err){
                         log.error('Req Aqi> get fail', geocode, date);
-                        cb(null);
+                        cb(err);
                         return;
                     }
 
@@ -227,9 +227,10 @@ controllerAqi.prototype.requestAqiData = function(geocode, From, To, timeOffset,
                     });
                 });
             },
-            function(err, aqiData){
+            function(err, aqiData) {
                 if(err){
                     log.error('Req Aqi> Fail to get AQI data');
+                    return callback(err);
                 }
                 var res = {
                     type : 'AQI',
diff --git a/server/controllers/worldWeather/controllerRequester.js b/server/controllers/worldWeather/controllerRequester.js
index 7bea04c..74b01b7 100644
--- a/server/controllers/worldWeather/controllerRequester.js
+++ b/server/controllers/worldWeather/controllerRequester.js
@@ -591,7 +591,9 @@ ControllerRequester.prototype.reqDataForTwoDays = function(req, callback){
                 collectorAqi.requestAqiData(req.geocode, 0, 0, req.timezone, function(err, aqiData){
                     if(err){
                         log.error('RQ> Fail to requestAqiData', meta);
-                        return cb('Fail to requestAqiData');
+                        log.warn(err);
+                        return cb();
+                        //return cb('Fail to requestAqiData');
                     }
 
                     log.info('RQ> AQI result : ', aqiData);
@@ -602,12 +604,17 @@ ControllerRequester.prototype.reqDataForTwoDays = function(req, callback){
         function(err, result){
             if(err){
                 log.error('RQ> Fail to request weather', meta);
+                return callback(err);
             }
 
             var res = {};
 
             if(result.length > 0){
                 result.forEach(function(item, index){
+                    if (item == undefined) {
+                        return;
+                    }
+
                     if(item.type === 'DSF'){
                         res.DSF = item;
                     }
```

**Comment by kimalec** [comment]
- [ ] iaqi 값중에서 h, p, t 값의 의미를 모르겠음.

```
  co: Number,
  h: Number,
  no2: Number,
  o3: Number,
  p: Number,
  pm10: Number,
  pm25: Number,
  so2: Number,
  t: Number
```
