### ISSUE TITLE
[WW] 502 at gcode=5.98,116.07

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1710]
오류로 죽음. timeZone이 문제인듯함.
```log
info: ## + /ww/010000/current/2?gcode=5.98,116.07 Time[ 2017-08-10T20:35:45.472Z] sID=Bp0yLB76aRWbgG176b1haeb1StC6lImI
info: WW> method=checkApiVersion, version=010000, sID=Bp0yLB76aRWbgG176b1haeb1StC6lImI
info: WW> go to next step method=checkApiVersion, version=010000, sID=Bp0yLB76aRWbgG176b1haeb1StC6lImI
info: TWW> geocode :  { lat: '5.98', lon: '116.07' } method=queryTwoDaysWeather, sID=Bp0yLB76aRWbgG176b1haeb1StC6lImI
info: DSF Timezone >  { min: NaN, ms: NaN } sID=Bp0yLB76aRWbgG176b1haeb1StC6lImI
warn: gDSF> There is no DSF data for  { lat: 5.98, lon: 116.07 } sID=Bp0yLB76aRWbgG176b1haeb1StC6lImI
error: TWW> Fail to get DSF data No Data method=queryTwoDaysWeather, sID=Bp0yLB76aRWbgG176b1haeb1StC6lImI
info: TWW> There is no correct weather data... try to request method=queryTwoDaysWeather, sID=Bp0yLB76aRWbgG176b1haeb1StC6lImI
info: WW> req url :  http://127.0.0.1:3000/req/all/req_two_days/?key=abcdefg&gcode=5.98,116.07&timezone=NaN sID=Bp0yLB76aRWbgG176b1haeb1StC6lImI
info: @@ + /req/all/req_two_days/?key=abcdefg&gcode=5.98,116.07&timezone=NaN Time[ 2017-08-10T20:35:45.810Z] sID=kivSwjibFxCWw3IEErN9K0tOV573d0jC UUID=
info: category:  all sID=kivSwjibFxCWw3IEErN9K0tOV573d0jC
info: command :  req_two_days sID=kivSwjibFxCWw3IEErN9K0tOV573d0jC
info: loging keys.....
info: ------------------------------------
info: OpenWeatherMap : key count(1)
info: WeatherUnloched : key count(1)
info: DarkSkyForecast : key count(1)
info: AQI : key count(1)
info: ------------------------------------
info: Keys have been loaded
info: RQ>  { lat: 5.98, lon: 116.07 } sID=kivSwjibFxCWw3IEErN9K0tOV573d0jC
info: RQ timezone>  NaN sID=kivSwjibFxCWw3IEErN9K0tOV573d0jC
info: same day
error: Invalid time
error: Invalid time
info: loging keys.....
info: ------------------------------------
info: OpenWeatherMap : key count(1)
info: WeatherUnloched : key count(1)
info: DarkSkyForecast : key count(1)
info: AQI : key count(1)
info: ------------------------------------
info: Keys have been loaded
info: same day
/Users/aleckim/WebstormProjects/server-TodayWeather/server/node_modules/newrelic/lib/transaction/tracer/index.js:191
      throw err
      ^

RangeError: Invalid time value
    at Date.toISOString (native)
    at /Users/aleckim/WebstormProjects/server-TodayWeather/server/controllers/worldWeather/controllerCollector.js:1431:63
    at /Users/aleckim/WebstormProjects/server-TodayWeather/server/node_modules/async/dist/async.js:1069:9
    at replenish (/Users/aleckim/WebstormProjects/server-TodayWeather/server/node_modules/async/dist/async.js:946:17)
    at /Users/aleckim/WebstormProjects/server-TodayWeather/server/node_modules/async/dist/async.js:950:9
    at _asyncMap (/Users/aleckim/WebstormProjects/server-TodayWeather/server/node_modules/async/dist/async.js:1067:5)
    at /Users/aleckim/WebstormProjects/server-TodayWeather/server/node_modules/async/dist/async.js:1153:16
    at Object.mapSeries (/Users/aleckim/WebstormProjects/server-TodayWeather/server/node_modules/async/dist/async.js:980:16)
    at /Users/aleckim/WebstormProjects/server-TodayWeather/server/controllers/worldWeather/controllerCollector.js:1424:15
    at /Users/aleckim/WebstormProjects/server-TodayWeather/server/controllers/worldWeather/controllerCollector.js:1326:9
    at Immediate.<anonymous> (/Users/aleckim/WebstormProjects/server-TodayWeather/server/node_modules/mongoose/lib/query.js:2181:28)
    at Immediate.<anonymous> (/Users/aleckim/WebstormProjects/server-TodayWeather/server/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at Immediate.wrapped [as _onImmediate] (/Users/aleckim/WebstormProjects/server-TodayWeather/server/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by kimalec** [comment]
아래도 모두 동일한 문제인듯하지만 확인 필요

gcode=21.13,-86.74
gcode=5.98,116.07
gcode=33.555,133.507
gcode=39.904,116.407
gcode=34.2,129.29
gcode=11.56,104.91
gcode=33.554,133.512
gcode=55.756,37.617
gcode=30.53,75.36
gcode=39.9,116.41
gcode=29.10,48.12
gcode=7.95,98.34
gcode=13.24,77.09
gcode=41.903,12.496
gcode=1.35,103.81
gcode=39.12,140.49
gcode=21.30,-157.85
gcode=41.903,12.496
gcode=41.90,12.48
gcode=-37.83,144.96
gcode=44.41,8.949999999999999
gcode=14.61,99.46
gcode=47.07,15.44
gcode=35.82,139.68
gcode=13.47,144.82
gcode=33.55,133.51
gcode=33.58,130.41
gcode=10.32,123.89
gcode=39.27,-76.8
gcode=14.02,99.53
gcode=23.795,90.405
gcode=39.12,140.49
gcode=48.86,2.35
gcode=23.69,120.96
gcode=39.27,-76.8
gcode=-17.42,-69.27

**Comment by kimalec** [comment]
- [ ] normalize로 인한 바다 인식 수정
- [ ] zero_results에 방안마련

**Comment by kimalec** [comment]
#1712 리뷰 코멘트 확인해주세요.

**Comment by kimalec** [comment]
- [ ] 두가지 값이 0임 "thisTime":[],"hourly":[]

**Comment by kimalec** [comment]
- [ ] timeZone 값이 없는 경우에는 address 정보 취득후에 time zone 계산
- [ ] 에러인 경우 바다날씨가 아니라 대륙날씨가 나오는가?
- [ ] address취득이 실패하면, local에서 시간정보를 제공
