### ISSUE TITLE
[bug] SyntaxError at dsfRequester.js:119:27

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1751]
https://api.darksky.net/forecast/xxxx/1.35,103.81,1505322000

```
SyntaxError: Unexpected token I in JSON at position 0
at Object.parse (native)
at Request._callback (/var/app/current/lib/DSF/dsfRequester.js:119:27)
at Request.self.callback (/var/app/current/node_modules/request/request.js:188:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request.<anonymous> (/var/app/current/node_modules/request/request.js:1171:10)
at emitOne (events.js:96:13)
at Request.emit (events.js:188:7)
at IncomingMessage.<anonymous> (/var/app/current/node_modules/request/request.js:1091:12)
at IncomingMessage.g (events.js:291:16)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at IncomingMessage.wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
at IncomingMessage.wrappedResponseEmit [as emit] (/var/app/current/node_modules/newrelic/lib/transaction/tracer/instrumentation/outbound.js:99:26)
at endReadableNT (_stream_readable.js:974:12)
at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
```

<img width="720" alt="2017-09-15 7 23 20" src="https://user-images.githubusercontent.com/6895272/30478303-7ec26472-9a4b-11e7-8e4c-012fb598f775.png">

**Comment by kimalec** [comment]
https://stackoverflow.com/questions/37593775/angular-ajax-unexpected-token-i-in-json-at-position-0

**Comment by kimalec** [comment]
임시 수정본 배포
```diff
diff --git a/lib/DSF/dsfRequester.js b/lib/DSF/dsfRequester.js
index fa02c56..1526807 100644
--- a/lib/DSF/dsfRequester.js
+++ b/lib/DSF/dsfRequester.js
@@ -116,7 +116,14 @@ dsfRequester.prototype.getData = function(url, retryCount, callback){
             return;
         }
 
-        var result = JSON.parse(body);
+        try {
+            var result = JSON.parse(body);
+        }
+        catch(e) {
+            log.warn(body);
+            callback(e);
+            return;
+        }
         //log.info(result);
         if(callback){
             callback(err, result);
@@ -124,4 +131,4 @@ dsfRequester.prototype.getData = function(url, retryCount, callback){
     });
 };
 
-module.exports = dsfRequester;
\ No newline at end of file
+module.exports = dsfRequester;
```
