### ISSUE TITLE
Ionic Deploy  Services 적용.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#180]
#65 에 추가로 Ionic deploy service를 적용하여, client web app만 수정되는 경우에 store update 없이 가능하게 만들기.

**Comment by kimalec** [comment]
http://docs.ionic.io/docs/deploy-overview

.io-config.json 필요함.

**Comment by kimalec** [comment]
https://github.com/driftyco/deploy-tutorial - deploy용 예제인데, docs와 내용이 좀 다른 부분들이 있음.

**Comment by kimalec** [comment]
ionic-platform-web-client 이 생기면서, ionic-service-analytics, ionic-service-core가 없어짐.

**Comment by kimalec** [comment]
It won't work on a browser, use a physical device or a simulator

**Comment by kimalec** [comment]
시나리오 필요함.
예제는 check updates button을 누르면 확인해서, 신규 아이템이 있다면 download button이 나타남.

**Comment by kimalec** [comment]
You can find information about the currently deployed version using the deploy.info function.

```js
var deploy = new Ionic.Deploy();
deploy.info().then(function(deployInfo) {
  // deployInfo will be a JSON object that contains
  // information relating to the latest update deployed
  // on the device
}, function() {}, function() {});
```

result
```js
{"deploy_uuid":"NO_DEPLOY_LABEL","binary_version":"0.1.0"}
```

**Comment by kimalec** [comment]
version은 config.xml과 package.json 두 군데를 변경시켜야 함.

**Comment by kimalec** [comment]
https://github.com/driftyco/ionic/issues/4452 - Ionic deploy does not work since IOS 9 

This sounds like the ATS settings that apple recently announced. You have to apply the following settings to you apps plist file.

https://gist.github.com/mlynch/284699d676fe9ed0abfa

Or you could try this plugin I wrote to automate the process.
https://www.npmjs.com/package/cordova-config-utils

**Comment by kimalec** [comment]
업데이트 실패하거나, 중간에 오류가 발생하면 앱을 지우고 다시 해야 함.

**Comment by kimalec** [comment]
cordova-config-utils 을 설치하면, build시에 config.xml을 보고 AndroidManifest.xml, IOS *-Info.plist 을 자동으로 수정해주는데, EACCES 발생함.

```bash
Running command: /Users/aleckim/WebstormProjects/TodayWeather/client/hooks/after_prepare/011_update_config.js /Users/aleckim/WebstormProjects/TodayWeather/client
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at Object.exports.spawn (child_process.js:995:9)
    at Object.exports.spawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:108:31)
    at runScriptViaChildProcessSpawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:189:23)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:115:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
```

**Comment by kimalec** [comment]
https://github.com/nordnet/cordova-hot-code-push 라고 code update해주는 plugin도 있음.
