### ISSUE TITLE
[WW] crash when it failed to get address 

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1816]
```
info: error_message=You have exceeded your rate-limit for this API., results=[], status=OVER_QUERY_LIMIT
TypeError: Cannot read property 'hasOwnProperty' of undefined
at Request._callback (/var/app/current/controllers/worldWeather/controllerWorldWeather.js:1025:41)
at Request.self.callback (/var/app/current/node_modules/request/request.js:186:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request.<anonymous> (/var/app/current/node_modules/request/request.js:1163:10)
at emitOne (events.js:96:13)
at Request.emit (events.js:188:7)
at IncomingMessage.<anonymous> (/var/app/current/node_modules/request/request.js:1085:12)
at IncomingMessage.g (events.js:291:16)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at IncomingMessage.wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
at IncomingMessage.wrappedResponseEmit [as emit] (/var/app/current/node_modules/newrelic/lib/transaction/tracer/instrumentation/outbound.js:99:26)
at endReadableNT (_stream_readable.js:974:12)
at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

**Comment by kimalec** [comment]
- [ ] 위치정보는 저장할 필요가 있어 보임(api 비용문제)
- [ ] 한번에 g api를 너무 많이 호출하고 있음
- [ ] try catch로 보호

**Comment by kimalec** [comment]
#1646 와 연관됨
