### ISSUE TITLE
Unexpected token < in JSON

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1881]
Wednesday 29 November, 2017 13:33:08 UTC
```
SyntaxError: Unexpected token < in JSON at position 0
at Object.parse (native)
at Request._callback (/var/app/current/lib/AQI/aqiRequester.js:72:27)
at Request.self.callback (/var/app/current/node_modules/request/request.js:186:22)
```

**Comment by kimalec** [comment]
- [ ] JSON.parse 사용시에 try catch 필요
- [ ] aqiRequester.prototype.getData의 error callback value 1, 2의 의미 정의가 필요

**Comment by kimalec** [comment]
- [ ] aqiRequester.prototype.getData의 error callback value 1, 2의 의미 정의가 필요 @pokers 설명이나 업데이트 부탁해요.
