### ISSUE TITLE
RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1888]
#716 
trace
```
info: One pixel size W: 0.011490256410256437 H: 0.009307381615598881
info: Airkorea Image > get Image Pixel map
info: Airkorea Image > Got pixel info for PM25
/var/app/current/node_modules/get-pixels/node-pixels.js:57 var ndata = new Uint8Array(nshape[0] * nshape[1] * nshape[2] * nshape[3])
```

```
RangeError: Array buffer allocation failed
at new Uint8Array (native)
at handleGIF (/var/app/current/node_modules/get-pixels/node-pixels.js:57:17)
at doParse (/var/app/current/node_modules/get-pixels/node-pixels.js:113:7)
at /var/app/current/node_modules/get-pixels/node-pixels.js:185:7
at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

**Comment by kimalec** [comment]
메모리 사용량을 가능하면 756MB에서 커버했으면 함.
1.5GB에서 동작한다면 당장은 1.5GB에서 유지하지만, 궁극적으로 분리 필요해 보임.

**Comment by pokers** [comment]
AWS 로그 상으로는 죽는문제가 보이지 않는데 확인 한번 부탁하고,
금일 DB로 부터 이미지 URL 가져와서 실제 이미지를 가지도 동작하는 내용 적용 후 다시 테스트 돌려주세요.

**Comment by kimalec** [comment]
t2.small에서 정상동작하고 있음.
