### ISSUE TITLE
[iOS][cordova] latest source에 대한 빌드환경 구성

### ISSUE THREAD

**Issue by seankim2** [WizardFactory/TodayWeather#1912]
latest source에 대한 빌드환경 구성
```
$brew update
$brew install nvm
$nvm install v6.12.1
$which node
$node --version
```

**Comment by seankim2** [comment]
* brew update시 아래 에러 발생
```
KwangHo-Kim-ui-MacBook-Pro:client mis2010$ brew update
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:16:in `<main>'
```
* 아래 대로 처리 한후 update 정상 처리
```
The problem mainly occurs after updating OS X to El Capitan (OS X 10.11) or macOS Sierra (macOS 10.12). This is mainly because of file permission issues with El Capitan’s or later macOS's new SIP process. Try changing permissions of /usr/local directory.

$ sudo chown -R $(whoami):admin /usr/local  
If it still doesn't work, use following steps and everything will be fine. This may be because homebrew is not updated.

1. open terminal  
2. $ cd /usr/local/Library/Homebrew  
3. $ git reset --hard  
4. $ git clean -df
5. $ brew update
```

**Comment by seankim2** [comment]
* brew install nvm 시 아래 에러 발생
```
KwangHo-Kim-ui-MacBook-Pro:Homebrew mis2010$ brew install nvm
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /Users/mis2010/Desktop/Development in PATH, mode 040777
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /Users/mis2010/Desktop/Development in PATH, mode 040777
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /Users/mis2010/Desktop/Development in PATH, mode 040777
==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
Already downloaded: /Users/mis2010/Library/Caches/Homebrew/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
==> Pouring portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /Users/mis2010/Desktop/Development in PATH, mode 040777
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /Users/mis2010/Desktop/Development in PATH, mode 040777
Updating Homebrew...
Error: Xcode alone is not sufficient on Sierra.
Install the Command Line Tools:
  xcode-select --install
```
* xcode-select --install 를 이용하여 소프트웨어 설치
* 이후 brew install nvm 설치 됨.

**Comment by seankim2** [comment]
* nvm 명령어가 안먹음
```
KwangHo-Kim-ui-MacBook-Pro:Homebrew mis2010$ nvm install v6.12.1
-bash: nvm: command not found
```
* 아래와 같이 처리
```
You should create NVM's working directory if it doesn't exist:

  mkdir ~/.nvm

Add the following to ~/.bash_profile or your desired shell
configuration file:

  export NVM_DIR="$HOME/.nvm"
  . "/usr/local/opt/nvm/nvm.sh"
```

**Comment by seankim2** [comment]
* npm install -g cordova@6 정상
* npm install -g ionic@2 정상
* Ionic reset state 에러
```
******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************
```
* npm install -g ios-deploy 정상

**Comment by seankim2** [comment]
* ionic state reset 에러
```
KwangHo-Kim-ui-MacBook-Pro:client mis2010$ ionic state reset
Uh oh! Looks like you're missing a module in your gulpfile:
Cannot find module 'shelljs'

Do you need to run `npm install`?
```
* npm install -g gulp로 해결
* ionic state reset
  * shelljs 모듈을 찾음
  * package.json을 다시 git checkout
  * node_modules 내부에 모듈을 모두 지우고, npm install
* ionic state reset 성공

**Comment by seankim2** [comment]
* gulp build_ios 빌드 성공
```
...    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --timestamp=none /Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/ios/build/emulator/TodayWeather.app



** BUILD SUCCEEDED **


[20:54:51] Finished 'build_ios' after 6.88 min
```
