### ISSUE TITLE
Callback was already called at kma.town.short.rss.controller.js:615:17

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1914]
```
Error: Callback was already called.\n    at /home/todayweather/TodayWeather/server/node_modules/async/dist/async.js:955:32\n    at /home/todayweather/TodayWeather/server/controllers/kma/kma.town.short.rss.controller.js:615:17\n    at /home/todayweather/TodayWeather/server/controllers/kma/kma.town.short.rss.controller.js:136:21\n    at Parser.<anonymous> (/home/todayweather/TodayWeather/server/node_modules/xml2js/lib/xml2js.js:493:18)\n    at emitOne (events.js:96:13)\n    at Parser.emit (events.js:188:7)\n    at Parser.exports.Parser.Parser.parseString (/home/todayweather/TodayWeather/server/node_modules/xml2js/lib/xml2js.js:512:16)\n    at Parser.parseString (/home/todayweather/TodayWeather/server/node_modules/xml2js/lib/xml2js.js:7:59)\n    at exports.parseString (/home/todayweather/TodayWeather/server/node_modules/xml2js/lib/xml2js.js:540:19)\n    at Request._callback (/home/todayweather/TodayWeather/server/controllers/kma/kma.town.short.rss.controller.js:120:9)\n    at Request.self.callback (/home/todayweather/TodayWeather/server/node_modules/request/request.js:188:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/home/todayweather/TodayWeather/server/node_modules/request/request.js:1171:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)
```

**Comment by kimalec** [comment]
```
2|www      | Error: Callback was already called.
2|www      |     at /home/todayweather/TodayWeather/server/node_modules/async/dist/async.js:955:32
2|www      |     at /home/todayweather/TodayWeather/server/controllers/kma/kma.town.short.rss.controller.js:632:21
2|www      |     at TownRss.parseShortRss (/home/todayweather/TodayWeather/server/controllers/kma/kma.town.short.rss.controller.js:333:13)
2|www      |     at /home/todayweather/TodayWeather/server/controllers/kma/kma.town.short.rss.controller.js:628:14
2|www      |     at /home/todayweather/TodayWeather/server/controllers/kma/kma.town.short.rss.controller.js:128:17
2|www      |     at Parser.<anonymous> (/home/todayweather/TodayWeather/server/node_modules/xml2js/lib/xml2js.js:493:18)
2|www      |     at emitOne (events.js:96:13)
2|www      |     at Parser.emit (events.js:188:7)
2|www      |     at Parser.exports.Parser.Parser.parseString (/home/todayweather/TodayWeather/server/node_modules/xml2js/lib/xml2js.js:512:16)
2|www      |     at Parser.parseString (/home/todayweather/TodayWeather/server/node_modules/xml2js/lib/xml2js.js:7:59)
2|www      |     at exports.parseString (/home/todayweather/TodayWeather/server/node_modules/xml2js/lib/xml2js.js:540:19)
2|www      |     at Request._callback (/home/todayweather/TodayWeather/server/controllers/kma/kma.town.short.rss.controller.js:120:9)
2|www      |     at Request.self.callback (/home/todayweather/TodayWeather/server/node_modules/request/request.js:188:22)
2|www      |     at emitTwo (events.js:106:13)
2|www      |     at Request.emit (events.js:191:7)
2|www      |     at Request.<anonymous> (/home/todayweather/TodayWeather/server/node_modules/request/request.js:1171:10)
```

**Comment by kimalec** [comment]
```
2|www      | Error: Callback was already called.
2|www      |     at /home/todayweather/TodayWeather/server/node_modules/async/dist/async.js:955:32
2|www      |     at /home/todayweather/TodayWeather/server/controllers/kma/kma.town.short.rss.controller.js:662:25
2|www      |     at /home/todayweather/TodayWeather/server/controllers/kma/kma.town.short.rss.controller.js:468:13
2|www      |     at Query.<anonymous> (/home/todayweather/TodayWeather/server/node_modules/mongoose/lib/model.js:3361:16)
2|www      |     at /home/todayweather/TodayWeather/server/node_modules/kareem/index.js:259:21
2|www      |     at /home/todayweather/TodayWeather/server/node_modules/kareem/index.js:127:16
2|www      |     at wrapped (/home/todayweather/TodayWeather/server/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
2|www      |     at _combinedTickCallback (internal/process/next_tick.js:67:7)
2|www      |     at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)
```

**Comment by kimalec** [comment]
- [ ] 정상적인 상태로 보이는데 parse에러 남(client에서 정상동작함)
 - [ ] callback 2번 불리는 원인이 파악 안되고 있음

**Comment by kimalec** [comment]
```diff
diff --git a/server/controllers/kma/kma.town.short.rss.controller.js b/server/controllers/kma/kma.town.short.rss.controller.js
index 2e9f501..bd8452f 100644
--- a/server/controllers/kma/kma.town.short.rss.controller.js
+++ b/server/controllers/kma/kma.town.short.rss.controller.js
@@ -123,7 +123,12 @@ TownRss.prototype.getShortRss = function(index, url, callback){
                 if(callback){
                     callback(self.ERROR);
                 }
+               return;
             }
+           if(callback){
+                callback(self.SUCCESS, result);
+            }
+/*
             try{
                 //log.info(result)
                 if(callback){
@@ -136,6 +141,7 @@ TownRss.prototype.getShortRss = function(index, url, callback){
                     callback(self.ERROR);
                 }
             }
+*/
         });
     });
 
@@ -244,6 +250,7 @@ TownRss.prototype.parseShortRss = function(index, data, callback){
         mx:0,
         my:0
     };
+var pubDate;
 
     //log.info('data:', data);
     //log.info('head:', data.wid.header[0]);
@@ -254,6 +261,7 @@ TownRss.prototype.parseShortRss = function(index, data, callback){
     //log.info('body:', data.wid.body[0].data[0]);
 
     try{
+log.info('parseShortRss', {index: index, data: data});
         coord.mx = parseInt(data.wid.header[0].x[0]);
         coord.my = parseInt(data.wid.header[0].y[0]);
         data.wid.body[0].data.forEach(function(item, index){
@@ -319,9 +327,7 @@ TownRss.prototype.parseShortRss = function(index, data, callback){
         });
 
         //log.info(dataList);
-        if(callback){
-            callback(self.SUCCESS, {mCoord: coord, pubDate: data.wid.header[0].tm[0], shortData: dataList});
-        }
+        pubdate = data.wid.header[0].tm[0];
     }
     catch(e){
         log.error('parse error! (%d)', index);
@@ -329,6 +335,9 @@ TownRss.prototype.parseShortRss = function(index, data, callback){
             callback(self.ERROR);
         }
     }
+        if(callback){
+            callback(self.SUCCESS, {mCoord: coord, pubDate: pubDate, shortData: dataList});
+        }
 };
 
 TownRss.prototype.lastestPubDate = function() {
@@ -363,6 +372,7 @@ TownRss.prototype.lastestPubDate = function() {
 TownRss.prototype.saveShortRss = function(index, newData, cb){
     var self = this;
 
+log.info({index: index, newData: newData});
     shortRssDb.find({mCoord: newData.mCoord}, function(err, list){
         if(err){
             log.error('fail to db item:', err);
@@ -800,4 +810,4 @@ TownRss.prototype.StartShortRss = function(){
     }, self.TIME_PERIOD_TOWN_RSS);
 };
```
위와 같이 내용이 수정되었으나, 아래와 같이 pubdate를 인식하지 못하고, parse에서 에러났음에도 save가 불림
```
3|www      | info: parseShortRss index=1829, header=[tm=[201712132000], ts=[6], x=[66], y=[126]], body=[data=[seq=0, hour=[24], day=[0], temp=[-12.0], tmx=[-999.0], tmn=[-999.0], sky=[1], pty=[0], wfKor=[맑음], wfEn=[Clear], pop=[0], r12=[0.0], s12=[0.0], ws=[0.7000000000000001], wd=[7], wdKor=[북서], wdEn=[NW], reh=[50], r06=[0.0], s06=[0.0], seq=1, hour=[3], day=[1], temp=[-13.0], tmx=[2.0], tmn=[-15.0], sky=[1], pty=[0], wfKor=[맑음], wfEn=[Clear], pop=[0], r12=[0.0], s12=[0.0], ws=[0.6000000000000001], wd=[1], wdKor=[북동], wdEn=[NE], reh=[65], r06=[0.0], s06=[0.0], seq=2, hour=[6], day=[1], temp=[-15.0], tmx=[2.0], tmn=[-15.0], sky=[1], pty=[0], wfKor=[맑음], wfEn=[Clear], pop=[0], r12=[0.0], s12=[0.0], ws=[0.6000000000000001], wd=[1], wdKor=[북동], wdEn=[NE], reh=[75], r06=[0.0], s06=[0.0], seq=3, hour=[9], day=[1], temp=[-10.0], tmx=[2.0], tmn=[-15.0], sky=[1], pty=[0], wfKor=[맑음], wfEn=[Clear], pop=[0], r12=[0.0], s12=[0.0], ws=[0.8], wd=[1], wdKor=[북동], wdEn=[NE], reh=[60], r06=[0.0], s06=[0.0], seq=4, hour=[12], day=[1], temp=[-1.0], tmx=[2.0], tmn=[-15.0], sky=[2], pty=[0], wfKor=[구름 조금], wfEn=[Partly Cloudy], pop=[10], r12=[0.0], s12=[0.0], ws=[1.2000000000000002], wd=[2], wdKor=[동], wdEn=[E], reh=[25], r06=[0.0], s06=[0.0], seq=5, hour=[15], day=[1], temp=[2.0], tmx=[2.0], tmn=[-15.0], sky=[3], pty=[0], wfKor=[구름 많음], wfEn=[Mostly Cloudy], pop=[20], r12=[0.0], s12=[0.0], ws=[0.9], wd=[3], wdKor=[남동], wdEn=[SE], reh=[10], r06=[0.0], s06=[0.0], seq=6, hour=[18], day=[1], temp=[-1.0], tmx=[2.0], tmn=[-15.0], sky=[3], pty=[0], wfKor=[구름 많음], wfEn=[Mostly Cloudy], pop=[20], r12=[0.0], s12=[0.0], ws=[0.6000000000000001], wd=[7], wdKor=[북서], wdEn=[NW], reh=[35], r06=[0.0], s06=[0.0], seq=7, hour=[21], day=[1], temp=[-6.0], tmx=[2.0], tmn=[-15.0], sky=[3], pty=[0], wfKor=[구름 많음], wfEn=[Mostly Cloudy], pop=[20], r12=[0.0], s12=[0.0], ws=[0.5], wd=[6], wdKor=[서], wdEn=[W], reh=[40], r06=[0.0], s06=[0.0], seq=8, hour=[24], day=[1], temp=[-8.0], tmx=[2.0], tmn=[-15.0], sky=[3], pty=[0], wfKor=[구름 많음], wfEn=[Mostly Cloudy], pop=[20], r12=[0.0], s12=[0.0], ws=[0.4], wd=[0], wdKor=[북], wdEn=[N], reh=[60], r06=[0.0], s06=[0.0], seq=9, hour=[3], day=[2], temp=[-8.0], tmx=[3.0], tmn=[-10.0], sky=[3], pty=[0], wfKor=[구름 많음], wfEn=[Mostly Cloudy], pop=[20], r12=[0.0], s12=[0.0], ws=[0.30000000000000004], wd=[0], wdKor=[북], wdEn=[N], reh=[60], r06=[0.0], s06=[0.0], seq=10, hour=[6], day=[2], temp=[-9.0], tmx=[3.0], tmn=[-10.0], sky=[2], pty=[0], wfKor=[구름 조금], wfEn=[Partly Cloudy], pop=[10], r12=[0.0], s12=[0.0], ws=[0.30000000000000004], wd=[6], wdKor=[서], wdEn=[W], reh=[65], r06=[0.0], s06=[0.0], seq=11, hour=[9], day=[2], temp=[-5.0], tmx=[3.0], tmn=[-10.0], sky=[2], pty=[0], wfKor=[구름 조금], wfEn=[Partly Cloudy], pop=[10], r12=[0.0], s12=[0.0], ws=[0.4], wd=[0], wdKor=[북], wdEn=[N], reh=[60], r06=[0.0], s06=[0.0], seq=12, hour=[12], day=[2], temp=[1.0], tmx=[3.0], tmn=[-10.0], sky=[3], pty=[0], wfKor=[구름 많음], wfEn=[Mostly Cloudy], pop=[20], r12=[0.0], s12=[0.0], ws=[0.8], wd=[5], wdKor=[남서], wdEn=[SW], reh=[30], r06=[0.0], s06=[0.0], seq=13, hour=[15], day=[2], temp=[3.0], tmx=[3.0], tmn=[-10.0], sky=[4], pty=[0], wfKor=[흐림], wfEn=[Cloudy], pop=[30], r12=[0.0], s12=[0.0], ws=[1.3], wd=[6], wdKor=[서], wdEn=[W], reh=[30], r06=[0.0], s06=[0.0], seq=14, hour=[18], day=[2], temp=[0.0], tmx=[3.0], tmn=[-10.0], sky=[4], pty=[0], wfKor=[흐림], wfEn=[Cloudy], pop=[30], r12=[0.0], s12=[0.0], ws=[1.3], wd=[4], wdKor=[남], wdEn=[S], reh=[50], r06=[0.0], s06=[0.0], seq=15, hour=[21], day=[2], temp=[-1.0], tmx=[3.0], tmn=[-10.0], sky=[4], pty=[0], wfKor=[흐림], wfEn=[Cloudy], pop=[30], r12=[0.0], s12=[0.0], ws=[0.8], wd=[4], wdKor=[남], wdEn=[S], reh=[55], r06=[0.5], s06=[0.8], seq=16, hour=[24], day=[2], temp=[0.0], tmx=[3.0], tmn=[-10.0], sky=[4], pty=[3], wfKor=[눈], wfEn=[Snow], pop=[60], r12=[0.0], s12=[0.0], ws=[0.6000000000000001], wd=[2], wdKor=[동], wdEn=[E], reh=[70], r06=[0.5], s06=[0.8]]]
3|www      | error: parse error! (1829)
3|www      | error: failed to parse short rss(1829)
3|www      | info:  index=1829, mx=66, my=126, pubDate=undefined, shortData=[ftm=201712132000, date=201712140000, temp=-12, tmx=-999, tmn=-999, sky=1, pty=0, wfKor=1, wfEn=1, pop=0, r12=0, s12=0, ws=0.7, wd=7, wdKor=4, wdEn=-1, reh=50, r06=0, s06=0, ftm=201712132000, date=201712140300, temp=-13, tmx=2, tmn=-15, sky=1, pty=0, wfKor=1, wfEn=1, pop=0, r12=0, s12=0, ws=0.6, wd=1, wdKor=3, wdEn=-1, reh=65, r06=0, s06=0, ftm=201712132000, date=201712140600, temp=-15, tmx=2, tmn=-15, sky=1, pty=0, wfKor=1, wfEn=1, pop=0, r12=0, s12=0, ws=0.6, wd=1, wdKor=3, wdEn=-1, reh=75, r06=0, s06=0, ftm=201712132000, date=201712140900, temp=-10, tmx=2, tmn=-15, sky=1, pty=0, wfKor=1, wfEn=1, pop=0, r12=0, s12=0, ws=0.8, wd=1, wdKor=3, wdEn=-1, reh=60, r06=0, s06=0, ftm=201712132000, date=201712141200, temp=-1, tmx=2, tmn=-15, sky=2, pty=0, wfKor=2, wfEn=2, pop=10, r12=0, s12=0, ws=1.2, wd=2, wdKor=1, wdEn=-1, reh=25, r06=0, s06=0, ftm=201712132000, date=201712141500, temp=2, tmx=2, tmn=-15, sky=3, pty=0, wfKor=3, wfEn=3, pop=20, r12=0, s12=0, ws=0.9, wd=3, wdKor=6, wdEn=-1, reh=10, r06=0, s06=0, ftm=201712132000, date=201712141800, temp=-1, tmx=2, tmn=-15, sky=3, pty=0, wfKor=3, wfEn=3, pop=20, r12=0, s12=0, ws=0.6, wd=7, wdKor=4, wdEn=-1, reh=35, r06=0, s06=0, ftm=201712132000, date=201712142100, temp=-6, tmx=2, tmn=-15, sky=3, pty=0, wfKor=3, wfEn=3, pop=20, r12=0, s12=0, ws=0.5, wd=6, wdKor=8, wdEn=-1, reh=40, r06=0, s06=0, ftm=201712132000, date=201712150000, temp=-8, tmx=2, tmn=-15, sky=3, pty=0, wfKor=3, wfEn=3, pop=20, r12=0, s12=0, ws=0.4, wd=0, wdKor=2, wdEn=-1, reh=60, r06=0, s06=0, ftm=201712132000, date=201712150300, temp=-8, tmx=3, tmn=-10, sky=3, pty=0, wfKor=3, wfEn=3, pop=20, r12=0, s12=0, ws=0.3, wd=0, wdKor=2, wdEn=-1, reh=60, r06=0, s06=0, ftm=201712132000, date=201712150600, temp=-9, tmx=3, tmn=-10, sky=2, pty=0, wfKor=2, wfEn=2, pop=10, r12=0, s12=0, ws=0.3, wd=6, wdKor=8, wdEn=-1, reh=65, r06=0, s06=0, ftm=201712132000, date=201712150900, temp=-5, tmx=3, tmn=-10, sky=2, pty=0, wfKor=2, wfEn=2, pop=10, r12=0, s12=0, ws=0.4, wd=0, wdKor=2, wdEn=-1, reh=60, r06=0, s06=0, ftm=201712132000, date=201712151200, temp=1, tmx=3, tmn=-10, sky=3, pty=0, wfKor=3, wfEn=3, pop=20, r12=0, s12=0, ws=0.8, wd=5, wdKor=7, wdEn=-1, reh=30, r06=0, s06=0, ftm=201712132000, date=201712151500, temp=3, tmx=3, tmn=-10, sky=4, pty=0, wfKor=4, wfEn=4, pop=30, r12=0, s12=0, ws=1.3, wd=6, wdKor=8, wdEn=-1, reh=30, r06=0, s06=0, ftm=201712132000, date=201712151800, temp=0, tmx=3, tmn=-10, sky=4, pty=0, wfKor=4, wfEn=4, pop=30, r12=0, s12=0, ws=1.3, wd=4, wdKor=5, wdEn=-1, reh=50, r06=0, s06=0, ftm=201712132000, date=201712152100, temp=-1, tmx=3, tmn=-10, sky=4, pty=0, wfKor=4, wfEn=4, pop=30, r12=0, s12=0, ws=0.8, wd=4, wdKor=5, wdEn=-1, reh=55, r06=0.5, s06=0.8, ftm=201712132000, date=201712160000, temp=0, tmx=3, tmn=-10, sky=4, pty=3, wfKor=7, wfEn=7, pop=60, r12=0, s12=0, ws=0.6, wd=2, wdKor=1, wdEn=-1, reh=70, r06=0.5, s06=0.8]
```

**Comment by kimalec** [comment]
아래와 같이 추가로 발생하였음

```log
error: parse error! (591)
error: failed to parse short rss(591)
Error: Callback was already called.
   at /home/todayweather/TodayWeather/server/node_modules/async/dist/async.js:955:32
   at /home/todayweather/TodayWeather/server/controllers/kma/kma.town.short.rss.controller.js:664:25
   at /home/todayweather/TodayWeather/server/controllers/kma/kma.town.short.rss.controller.js:395:17
```
