### ISSUE TITLE
air_foreacast가 빠지는 경우 발생

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1950]
testGetAllTown로 test하다가 발견
특정 시점에 air_forecast가 없이 전달됨

관련 이슈 #716 미세먼지 예측모델 파싱

```
to have property air_forecast
    at Assertion.fail (/Users/aleckim/WebstormProjects/server-TW/server/node_modules/should/lib/assertion.js:92:17)
    at Assertion.value [as property] (/Users/aleckim/WebstormProjects/server-TW/server/node_modules/should/lib/assertion.js:164:19)
    at Test.<anonymous> (/Users/aleckim/WebstormProjects/server-TW/server/test/e2e/testGetAllTown.js:117:46)
```

**Comment by kimalec** [comment]
#2082에서 디비형태로 변경되어 현 이슈 없어짐
