### ISSUE TITLE
 'header' of undefined at Request._callback(controllerHealthDay.js:195

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1982]
```
TypeError: Cannot read property 'header' of undefined
    at Request._callback (/home/todayweather/TodayWeather/server/controllers/controllerHealthDay.js:195:36)
    at Request.self.callback (/home/todayweather/TodayWeather/server/node_modules/request/request.js:186:22)
```
위와 같은 에러가 발생하는 경우가 있음.

**Comment by kimalec** [comment]
연속으로 데이터 요청시에 "ReturnCode=30 errMsg=SERVICE KEY IS NOT REGISTERED ERROR" 가 빈번하게 발생하고 있음.
