### ISSUE TITLE
[WW] undefined at controllerWorldWeather.js:1046

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#2007]
latlng=37.567,0.000인 경우 오류
바다인경우라도 darksky에서 날씨는 제공하는 것으로 보임. 조정 필요
```
info: https://maps.googleapis.com/maps/api/geocode/json?latlng=37.567,0.000&language=en
error: TWW> Fail to get addressByGeocode : TypeError: Cannot read property 'hasOwnProperty' of undefined
at Request._callback (/var/app/current/controllers/worldWeather/controllerWorldWeather.js:1046:45)
at Request.self.callback (/var/app/current/node_modules/request/request.js:186:22)
```

**Comment by pokers** [comment]
기존 timezone값을 가져오지 날씨 데이터를 구성하지 못했던 문제 수정후 정상동작함.
#2131
