### ISSUE TITLE
undefined at function.geoinfo.js:80

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#2016]
```
2018-01-04T23:00:01.809Z	fe9c94f5-f1a2-11e7-91c7-85b5bf2563d6	{ _request: { url: 'http://54.83.173.70/v000901/dsf/coord/36.65,138.19?distanceUnit=m&temperatureUnit=C&airUnit=airkorea&windSpeedUnit=m/s&precipitationUnit=mm&pressureUnit=hPa' } }
2018-01-04T23:00:05.024Z	fe9c94f5-f1a2-11e7-91c7-85b5bf2563d6	{ _request: { url: 'http://twservice-env.us-east-1.elasticbeanstalk.com/v000901/dsf/coord/36.65,138.19?distanceUnit=m&temperatureUnit=C&airUnit=airkorea&windSpeedUnit=m/s&precipitationUnit=mm&pressureUnit=hPa' } }
2018-01-04T23:00:08.223Z	fe9c94f5-f1a2-11e7-91c7-85b5bf2563d6	{ requests: { result: false } }
2018-01-04T23:00:08.223Z	fe9c94f5-f1a2-11e7-91c7-85b5bf2563d6	TypeError: Cannot set property 'name' of undefined
at forEach (/var/task/function.geoinfo.js:80:31)
at Array.forEach (native)
at GeoInfo.importGeoInfo (/var/task/function.geoinfo.js:77:48)
at _requests.err (/var/task/function.weather.js:163:38)
at async.someSeries (/var/task/function.weather.js:58:13)
at /var/task/node_modules/async/dist/async.js:2792:17
at /var/task/node_modules/async/dist/async.js:473:16
at replenish (/var/task/node_modules/async/dist/async.js:993:25)
at iterateeCallback (/var/task/node_modules/async/dist/async.js:983:17)
at /var/task/node_modules/async/dist/async.js:958:16
```

**Comment by kimalec** [comment]
tw-svc에서 weather data를 못 받으면 발생함
