### ISSUE TITLE
Req Aqi> get fail { lat: 35.664, lon: 0 }

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#2038]
```
03:28:43 error: Req Aqi> get fail { lat: 35.664, lon: 0 } undefined
03:28:43 warn: Error: AQI> there is no coordinate at aqiRequester.getAqiData (/var/app/current/lib/AQI/aqiRequester.js:24:18) at /var/app/current/controllers/worldWeather/controllerAqi.js:282:27 at /var/app/current/node_modules/async/dist/async.js:1121:9 at replenish (/var/app/current/node_modules/async/dist/async.js:998:17) at /var/app/current/node_modules/async/dist/async.js:1002:9
03:28:43 info: RQ> AQI result : type=AQI, lat=35.664, lon=0, , date=0, dateObj=Thu Jan 01 1970 00:00:00 GMT+0000 (UTC), timeOffset=1, data=[]
03:28:43 info: date : 2018-01-09T00:00:00.000Z
03:28:43 2018-01-09T03:28:43+0000 <error> controllerCollector.js:1435 () Req Dsf> get fail { lat: 35.664, lon: 0 } 1515456000
```

**Comment by kimalec** [comment]
merge후 tw-test에서 동작확인함.
