### ISSUE TITLE
[iOS][widget] 180111 iOS Widget 관련 수정요 사항

### ISSUE THREAD

**Issue by seankim2** [WizardFactory/TodayWeather#2091]
* Daum Key관련 function들 삭제 ( 서버에서 처리하는 것으로 변경됨 )
* 국내 사용자가 해외로 나갔을 때 예외 처리 ( nsdCurCity 중점 확인 필요 )
* cityList는 location만 업데이트. 
  * 현재위치 true 지역만 계속적으로 update. 
  * 현재로서는 지금은 readonly로만 사용. 추후 안드로이드와 통합
  * 날씨정보는 다른 Dictionary 로 관리
* KR로 들어오는 건 즉 주소 뒤집어 지는 건… location으로 들어온걸 overwrite 함으로써 해결해야함
  * location이 없는 경우는 kmaaddr(현재코드상황)로 보내는 경우가 아니라 location정보를 받아서 weather coord로 요청 필요.
* 추가적으로 불필요한 코드 삭제 ( 날씨데이터는 coord로 작업됨 - Global과 KR 함수 통일 )

**Comment by seankim2** [comment]
* Daum으로 request 하는 로직 및 관련 Array 삭제
* Daum Key와 관련된 retry 로직도 삭제
* DAUM Request URL 삭제
* TodayWeatherUtil내에 shuffle 함수 삭제
* daumkey get/set 함수 삭제

**Comment by seankim2** [comment]
* NSLog 내의 array count를 %ld로 변경후 unsigned long으로 type casting
* 국내 사용자가 해외 나갔을 때라도 current Postion이 true이면 새로운 coord를 받기에 문제 없음
  * current position이 false이더라도 기존에 저장된 KR/Global을 사용하기에 문제 없음.
  * 예상하지 못한 예외상황에 대한 자세한 이슈내용이나 문제가 발생된 재현 경로가 필요함.

**Comment by seankim2** [comment]
* 날씨정보를 따로 저장하기 위해 saveWeatherInfo 함수내에 UserDefault를 변경
  * group.net.wizardfactory.todayweather SuiteName대신에 group.net.wizardfactory.todayweather.weatherinfo 사용예정
* Dictionary에는 index와 weather 정보만 저장
* 이전 데이터를 사용시에는 index로 array에서 watherinfo Dictionary를 찾아서 사용하는 방식으로 변경예정

**Comment by seankim2** [comment]
* gulp build_ios시 아래 에러 발생
```
Installing "cordova-plugin-inapppurchase" for ios
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-inapppurchase':CordovaError: Uh oh!
"/Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/ios/TodayWeather/Plugins/cordova-plugin-inapppurchase/RMStore.m" already exists!
    at copyNewFile (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/ios/cordova/lib/plugman/pluginHandlers.js:320:15)
    at installHelper (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/ios/cordova/lib/plugman/pluginHandlers.js:240:13)
    at install (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/ios/cordova/lib/plugman/pluginHandlers.js:34:13)
    at Object.process (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at Api.addPlugin (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/ios/cordova/Api.js:235:10)
    at handleInstall (/Users/mis2010/.nvm/versions/node/v6.12.1/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:611:6)
    at /Users/mis2010/.nvm/versions/node/v6.12.1/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:407:28
    at _fulfilled (/Users/mis2010/.nvm/versions/node/v6.12.1/lib/node_modules/cordova/node_modules/q/q.js:787:54)
Error: Uh oh!
"/Users/mis2010/workjs/TodayWeather/TodayWeather/client/platforms/ios/TodayWeather/Plugins/cordova-plugin-inapppurchase/RMStore.m" already exists!
[11:06:13] 'build_ios' errored after 10 min
[11:06:13] Error in plugin 'gulp-shell'
Message:
    Command `cordova plugin add cordova-plugin-inapppurchase` failed with exit code 1
KwangHo-Kim-ui-MacBook-Pro:client mis2010$ cordova plugin remove cordova-plugin-inapppurchase
Uninstalling cordova-plugin-inapppurchase from ios
Removing "cordova-plugin-inapppurchase"
```

**Comment by seankim2** [comment]
* 에뮬레이터를 이용하면 NSDefaults가 null임...
* device를 이용하여 run시에는 아래 로그가 나오면서 실행이 안됨...
```
Finished running com.apple.spingboard on iPhone
```
* widget실행을 device에서 실행가능하도록 해야지 원할한 디버깅이 가능해 보임

**Comment by seankim2** [comment]
* 171201 source에서도 widget device실행안됨.
  * source tree 구조 변경이 아닌 xcode 버그인듯으로 보임...
* gulp.js내의 inapppurchase 삭제 후 build_ios빌드 성공함.

**Comment by seankim2** [comment]
* 다른 sample을 download받아도 widget만 deviced에서 동작하지 않음
* device의 문제인지 iphone5s에서도 테스트해봐야함.....

**Comment by seankim2** [comment]
* iphone5s에서 widget 샘플앱은 실행됨
* 오늘날씨앱은 아래 에러가 팝업으로 발생
```
Could not attach to pid : “313”
Ensure “net.wizardfactory.todayweather.todayext” is not already running, and mis2010 has permission to debug it.
```

**Comment by seankim2** [comment]
* 1월 24일에 하드카피한 백업본에서 iphone5s는 정상적으로 widget이 실행됨.
* 현재상황
  * 에뮬에서는 실행되지만 device에서는 동작안하는 경우 발생
  * iphone8(ios ver 11.2.2)은 widget 동작안함.
  * iphone5s(ios ver 10.3.3)에서는 동작함 
  * 현재 작업본은 둘다 widget이 동작하지 않음
    * 최신 버전으로 merget후 gulp build_ios 한 것이 최신버젼이어서 이와 관련이 있는 지 확인이 필요
    * 1/24일 버젼은 최신소스와 merge 하지 않았음...
    * 단순한 source의 conflict로 인한 이슈일 수도 있을 것으로 예상됨...
       * 아래와 같은 경우가 있다고 함. 
          * https://stackoverflow.com/questions/44651029/xcode-9-beta-could-not-attach-to-pid

**Comment by seankim2** [comment]
* 1월 24일 소스 형상에서 동작하므로 복사해서 사용
  * 이 이슈이후에 Pull Request후 최신소스와 merge후에도 정상적인지 확인은 필요함
* iphone5s로 디버깅 가능 
  * iphone8은 디버깅 안됨
* saveWeather내에 index와 weatherData만 dictionary화하여 , 'group.net.wizardfactory.todayweather.weatherdata' UserDefault에 save

**Comment by seankim2** [comment]
* mCityDictList 대신에 weatherInfo List인 mWeatherDataList 생성
* CityInfo내의 weatherData Dictionary는 삭제해야할 지 확인 필요
* updateXXXX function들에 대해서도 weatherData 삭제해야함.
* processPrevData내에서 mCityDictList 대신에 mWeatehrDataList 사용
* WeatherData는 공유된 UserDefault가 아닌 widget자체적으로 save/load 되도록 디버깅해야함...

**Comment by seankim2** [comment]
* saveWeatherInfo내에서 저장하는 로직 변경후 아래 에러 발생
```
2018-02-02 00:55:01.022851+0900 widget[257:6726] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM setObject:atIndexedSubscript:]: index 1 beyond bounds for empty array'
*** First throw call stack:
(0x1894f6fe0 0x187f58538 0x1894e6908 0x10003ebe8 0x10003ffbc 0x10003fe48 0x189b0134c 0x189b19048 0x189fc6854 0x189f0b7b0 0x189efbb68 0x189fc8bf0 0x1883ae9a0 0x1883bcad4 0x1883b22cc 0x1883bea50 0x1883be7d0 0x1885b7100 0x1885b6cac)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by seankim2** [comment]
* mWeatherDataList가 비어있을때에 대한 exception 처리 추가 이후 이슈 제거됨.

**Comment by seankim2** [comment]
* group.net.wizardfactory.todayweather.weatherdata suitename으로 저장한 후 저장된 데이터를 출력
```
nssWeatherList : {"weatherDataList":[{"index":2,"weatherData":{"airInfo":{"last":{"aqiStr":"좋음","o3Grade":1,"stationName":"New York","coValue":0.493,"no2Grade":1,"
...
```
* 재시작후 로드를 했지만 아무것도 저장이 안됨
```
[User Defaults] Failed to read values in CFPrefsPlistSource<0x170118420> (Domain: group.net.wizardfactory.todayweather.weatherData, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
2018-02-10 14:03:54.480921+0900 widget[273:15933] nssWeatherList: (null)
2018-02-10 14:03:54.480965+0900 widget[273:15933] User Default WD: (null)
2018-02-10 14:03:54.480997+0900 widget[273:15933] [mWeatherDataList count] : 0
```

**Comment by seankim2** [comment]
* 저장이 안되는 문제 원인파악해야됨...
* cordova plugin ( cordova preference???) 이슈
  * 메인앱과의 연동이 아닌 native 자체적인 것이므로 plugin 이슈는 아닌 것으로 파악됨.
* Domain 이슈
  * Domain: group.net.wizardfactory.todayweather.weatherData... 구글링이 필요해 보임
* UserDefaults의 대안
  * NSFileManager를 이용하여 file로 저장하는 방안이 있음.

**Comment by seankim2** [comment]
* 앱이 켜진 상태에서는 정상적을 NSUserDefaults가 저장됨.
* 앱 시작시 로드가 안되는 이유는 domain의 마지막 sentence가 weatherData로 되어 있음
  * weatherdata로 저장했음. Data의 D를 대문자로 load해서 생긴 문제임
* jsonDictWD의 Key도 weatherData가 아닌 weatherDataList를 설정해야함.
* 정상적으로 저장됨을 확인함
```
2018-02-10 23:30:06.223334+0900 widget[433:77523] User Default WD: {
    weatherDataList =     (
                {
            index = 0;
            weatherData =             {
                index = 0;
                weatherData =                 {
                    address = "\Uc11c\Uc6b8\Ud2b9\Ubcc4\Uc2dc \Uc911\Uad6c \Uba85\Ub3d9";
                    airInfo =                     {
                        forecastPubDate = "2018-02-10 23:00";
                        forecastSource = airkorea;
                        last =                         {
...
```
