### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#2125]
```js
error: requestData : ERROR !!! in event dataCompleted
error:  RangeError: Maximum call stack size exceeded
    at defineProperty (native)
    at Logger.log (/home/ec2-user/tw-gather/server/node_modules/winston/lib/winston/logger.js:121:36)
    at target.(anonymous function) [as silly] (/home/ec2-user/tw-gather/server/node_modules/winston/lib/winston/common.js:54:18)
     at /home/ec2-user/tw-gather/server/controllers/controllerManager.js:1025:25
     at /home/ec2-user/tw-gather/server/node_modules/async/dist/async.js:1121:9
     at replenish (/home/ec2-user/tw-gather/server/node_modules/async/dist/async.js:998:17)
     at iterateeCallback (/home/ec2-user/tw-gather/server/node_modules/async/dist/async.js:983:17)
     at /home/ec2-user/tw-gather/server/node_modules/async/dist/async.js:958:16
     at /home/ec2-user/tw-gather/server/node_modules/async/dist/async.js:1123:13
     at /home/ec2-user/tw-gather/server/controllers/controllerManager.js:1029:21
     at /home/ec2-user/tw-gather/server/node_modules/async/dist/async.js:1121:9
     at replenish (/home/ec2-user/tw-gather/server/node_modules/async/dist/async.js:998:17)
     at iterateeCallback (/home/ec2-user/tw-gather/server/node_modules/async/dist/async.js:983:17)
     at /home/ec2-user/tw-gather/server/node_modules/async/dist/async.js:958:16
     at /home/ec2-user/tw-gather/server/node_modules/async/dist/async.js:1123:13
     at /home/ec2-user/tw-gather/server/controllers/controllerManager.js:1029:21
```

**Comment by kimalec** [comment]
async.mapSeries 의 가 내부적으로 어떻게 되어 있는지 모르겠지만 stack 자체가 깊지는 않은 것 같은데 이상하네요.
retryCount를 20에서 2로 변경해도 발생함.

**Comment by kimalec** [comment]
collectInfo.requestData가 깊어서 발생하는 이슈일 수도 있을듯함.
