### ISSUE TITLE
MongoError: E11000 duplicate key error collection

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#2134]
```log
4|www      | error:  MongoError: E11000 duplicate key error collection: twonlyone.pushes index: _id_ dup key: { : ObjectId('59936e8e8dc93eb26b3852a6') }
4|www      |     at Function.MongoError.create (/home/ec2-user/tw-push/server/node_modules/mongodb-core/lib/error.js:31:11)
4|www      |     at toError (/home/ec2-user/tw-push/server/node_modules/mongodb/lib/utils.js:114:22)
4|www      |     at /home/ec2-user/tw-push/server/node_modules/mongodb/lib/collection.js:1008:67
4|www      |     at /home/ec2-user/tw-push/server/node_modules/mongodb/lib/apm.js:249:9
4|www      |     at /home/ec2-user/tw-push/server/node_modules/mongodb/lib/apm.js:249:9
4|www      |     at /home/ec2-user/tw-push/server/node_modules/mongodb/lib/apm.js:249:9
4|www      |     at /home/ec2-user/tw-push/server/node_modules/mongodb/lib/apm.js:249:9
4|www      |     at /home/ec2-user/tw-push/server/node_modules/mongodb/lib/apm.js:249:9
4|www      |     at /home/ec2-user/tw-push/server/node_modules/mongodb/lib/apm.js:249:9
4|www      |     at commandCallback (/home/ec2-user/tw-push/server/node_modules/mongodb-core/lib/topologies/server.js:1194:9)
4|www      |     at Callbacks.emit (/home/ec2-user/tw-push/server/node_modules/mongodb-core/lib/topologies/server.js:119:3)
4|www      |     at Connection.messageHandler (/home/ec2-user/tw-push/server/node_modules/mongodb-core/lib/topologies/server.js:358:23)
4|www      |     at Socket.<anonymous> (/home/ec2-user/tw-push/server/node_modules/mongodb-core/lib/connection/connection.js:292:22)
4|www      |     at emitOne (events.js:96:13)
4|www      |     at Socket.emit (events.js:188:7)
4|www      |     at readableAddChunk (_stream_readable.js:176:18)
```

**Comment by kimalec** [comment]
https://github.com/Automattic/mongoose/issues/2471#issuecomment-365042484

**Comment by kimalec** [comment]
update 요청시에 없는 필드 id에 대하여 조건식을 걸어서 문제가 되었음.
우선 cityIndex를 id로 해서 업데이트를 모두 한 이후에 다시 update 조건을 기존으로 유지해야 함.

**Comment by kimalec** [comment]
#1701 #2130
