### ISSUE TITLE
 An AttributeValue may not contain an empty string for key :kmaAddress

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#2135]
kmaAddress에 name2의 string length가 0인 문제
```log
2018-02-16T23:32:13.062Z	9d5ab65c-1371-11e8-a70e-5d34997b8253	{ ValidationException: ExpressionAttributeValues contains invalid value: One or more parameter values were invalid: An AttributeValue may not contain an empty string for key :kmaAddress
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
message: 'ExpressionAttributeValues contains invalid value: One or more parameter values were invalid: An AttributeValue may not contain an empty string for key :kmaAddress',
code: 'ValidationException',
time: 2018-02-16T23:32:13.053Z,
requestId: 'AR6RU8CGPANHUQ4VI263VL63IRVV4KQNSO5AEMVJF66Q9ASUAAJG',
statusCode: 400,
retryable: false,
retryDelay: 35.74233069040308 }
```

**Comment by kimalec** [comment]
```
{ geoInfo: 
{ country: 'KR',
address: '세종특별자치시 전의면',
label: '전의면',
kmaAddress: { name1: '세종특별자치시', name2: '', name3: '전의면' },
loc: [ 36.597, 127.175 ],
lang: 'ko',
id: '36.597,127.175,ko' } }
```
