### ISSUE TITLE
'date' of undefined at ControllerWWUnits.convertUnits

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#2140]
url = http://localhost:3000/v000901/dsf/coord/35.709,139.732?distanceUnit=km&temperatureUnit=C&airUnit=airnow&windSpeedUnit=m/s&precipitationUnit=mm&pressureUnit=mmHg
```
error: TypeError: Cannot read property 'date' of undefined
at ControllerWWUnits.convertUnits (/var/app/current/controllers/worldWeather/controller.ww.units.js:39:38)
at Layer.handle (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
at Layer.wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
at Layer.wrappedLayerHandleRequest [as handle_request] (/var/app/current/node_modules/newrelic/lib/instrumentation/express.js:364:14)
at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
at cleanup (/var/app/current/node_modules/newrelic/lib/instrumentation/express.js:377:54)
at self.dataSort (/var/app/current/controllers/worldWeather/controllerWorldWeather.js:1673:9)
at Layer.handle (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
at Layer.wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
at Layer.wrappedLayerHandleRequest [as handle_request] (/var/app/current/node_modules/newrelic/lib/instrumentation/express.js:364:14)
at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
at cleanup (/var/app/current/node_modules/newrelic/lib/instrumentation/express.js:377:54)
at self.mergeAqi (/var/app/current/controllers/worldWeather/controllerWorldWeather.js:1610:9)
at Layer.handle (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
```

```
TypeError: Cannot read property 'hasOwnProperty' of undefined
at ControllerTown24h.makeSummaryWeather (/var/app/current/controllers/controllerTown24h.js:1180:20)
at ControllerWWUnits.makeSummary (/var/app/current/controllers/worldWeather/controller.ww.units.js:80:47)
at Layer.handle (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
at Layer.wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
at Layer.wrappedLayerHandleRequest [as handle_request] (/var/app/current/node_modules/newrelic/lib/instrumentation/express.js:364:14)
at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
at cleanup (/var/app/current/node_modules/newrelic/lib/instrumentation/express.js:377:54)
at self.makeAirInfo (/var/app/current/controllers/worldWeather/controllerWorldWeather.js:1627:9)
at Layer.handle (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
at Layer.wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
at Layer.wrappedLayerHandleRequest [as handle_request] (/var/app/current/node_modules/newrelic/lib/instrumentation/express.js:364:14)
at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
at cleanup (/var/app/current/node_modules/newrelic/lib/instrumentation/express.js:377:54)
at ControllerWWUnits.convertUnits (/var/app/current/controllers/worldWeather/controller.ww.units.js:73:9)
```

**Comment by kimalec** [comment]
yesterday 데이타가 없어서 에러가 발생함.

**Comment by kimalec** [comment]
과거 데이터가 없어서 yesterday를 못 찾았음.
과거 데이터를 저장할때 save를 기다리지 않고 다음 find and save를 하면서 이전 데이터가 저장되지 않는게 문제였음
