### ISSUE TITLE
디비에서 날씨 데이터 가져오는 경우, current 못 찾는 문제

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#2148]
```
info: DSF current> CDdate : 2018.02.20 08:19 sID=hTtrwb37jRJFbD_Pg6MOkIic6tpeG5yq
info: DSF Hourly> SDate : 2018.02.18 08:00 sID=hTtrwb37jRJFbD_Pg6MOkIic6tpeG5yq
info: DSF Hourly> yesterday : 2018.02.19 08:00 sID=hTtrwb37jRJFbD_Pg6MOkIic6tpeG5yq
info: DSF Hourly> CDate : 2018.02.20 08:00 sID=hTtrwb37jRJFbD_Pg6MOkIic6tpeG5yq
info: DSF yesterday > Found yesterday data 2018.02.19 08:00 sID=hTtrwb37jRJFbD_Pg6MOkIic6tpeG5yq
error: TypeError: Cannot read property 'date' of undefined at ControllerWWUnits.convertUnits (/var/app/current/controllers/worldWeather/controller.ww.units.js:39:38) at Layer.handle (/var/app/current/node_modules/express/lib/router/layer.js:95:5) at Layer.wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28) at Layer.wrappedLayerHandleRequest [as
i-084f6d603ca2d8288
error: TypeError: Cannot read property 'date' of undefined
at ControllerWWUnits.convertUnits (/var/app/current/controllers/worldWeather/controller.ww.units.js:39:38)
```
위에 로그에 따르면 yesterday는 찾았지만 current를 찾지 못했음.

local에서 재현된 것을 보면 _compareDateString는 시간까지 비교하는데, 앞자리가 변경되면서 찾지 못 하는 문제가 발생함.
```
info: DSF current> CDdate :  2018.02.20 09:11 sID=JEoUnUXPyQWcT5YdDSGq1d7jrSS2GPQA
info: Compare Date 2018.02.20 09:11 2018.02.19 01:00
info: Compare Date 2018.02.20 09:11 2018.02.20 01:00
info: Compare Date 2018.02.20 09:11 2018.02.20 08:45
```

**Comment by kimalec** [comment]
데이터를 갱신하는 기준은 UTC 정각이고, current를 찾는 기준은 localtime으로 동일 시간이기 때문에 timeZone이 30분, 15분 단위로 끊어지는 지역은 틈이 있음.
