### ISSUE TITLE
kakao story 에서 스토리에 공유시에 에러 발생

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#22]
카카오스토리에서 '스토리에 공유' 시에 아무글도 안쓰는 경우 발생하는 에러
![2015-07-25 06 50 07](https://cloud.githubusercontent.com/assets/6895272/8885346/9e0dbe10-3299-11e5-93f1-1c6fc53bedbd.png)
아래 상황
![2015-07-25 06 52 35](https://cloud.githubusercontent.com/assets/6895272/8885369/c222c2f0-3299-11e5-80ff-53152973749d.png)

관련 로그
```
» 25 Jul 2015 03:04:45.788 2015-07-24 18:04:45.497404+00:00 app web.1 - - error: Error: content is not String at Object.blogConvert.getHashTags (/app/controllers/blogConvert.js:481:24) at _pushPostsFromKakao (/app/routes/kakao.js:254:50) at /app/routes/kakao.js:296:17 at /app/routes/kakao.js:691:9 at /app/controllers/requestEx.js:72:13 at Function.req.checkError (/app/controllers/requestEx.js:55:9) at Request._callback (/app/controllers/requestEx.js:68:13) at Request.self.callback (/app/node_modules/request/request.js:123:22) at Request.emit (events.js:110:17) at Request.<anonymous> (/app/node_modules/request/request.js:1047:14) ExceptionFatal Context
» 25 Jul 2015 03:04:46.815 2015-07-24 18:04:46.525276+00:00 app web.1 - - error: Error: content is not String at Object.blogConvert.getHashTags (/app/controllers/blogConvert.js:481:24) at _pushPostsFromKakao (/app/routes/kakao.js:254:50) at /app/routes/kakao.js:343:17 at /app/routes/kakao.js:691:9 at /app/controllers/requestEx.js:72:13 at Function.req.checkError (/app/controllers/requestEx.js:55:9) at Request._callback (/app/controllers/requestEx.js:68:13) at Request.self.callback (/app/node_modules/request/request.js:123:22) at Request.emit (events.js:110:17) at Request.<anonymous> (/app/node_modules/request/request.js:1047:14) ExceptionFatal Context
» 25 Jul 2015 03:04:52.382 2015-07-24 18:04:52.090462+00:00 app web.1 - - error: Error: content is invalid at Object.blogConvert.removeHtmlTags (/app/controllers/blogConvert.js:226:24) at Object.blogConvert.convertPostToPlainContent (/app/controllers/blogConvert.js:271:35) at Object.handle (/app/routes/twitter.js:441:8) at next_layer (/app/node_modules/express/lib/router/route.js:103:13) at Route.dispatch (/app/node_modules/express/lib/router/route.js:107:5) at /app/node_modules/express/lib/router/index.js:205:24 at param (/app/node_modules/express/lib/router/index.js:286:14) at param (/app/node_modules/express/lib/router/index.js:298:16) at Function.proto.process_params (/app/node_modules/express/lib/router/index.js:314:3) at next (/app/node_modules/express/lib/router/index.js:199:19) ExceptionFatal Context
» 25 Jul 2015 03:04:52.666 2015-07-24 18:04:52.376419+00:00 app web.1 - - error: Error: content is not String at Object.blogConvert.getHashTags (/app/controllers/blogConvert.js:481:24) at Object.blogConvert.makeLimitString (/app/controllers/blogConvert.js:403:36) at /app/controllers/blogConvert.js:321:35 at /app/node_modules/async/lib/async.js:251:17 at done (/app/node_modules/async/lib/async.js:132:19) at /app/node_modules/async/lib/async.js:32:16 at /app/node_modules/async/lib/async.js:248:21 at /app/node_modules/async/lib/async.js:572:34 at /app/controllers/blogConvert.js:310:28 at /app/controllers/blogConvert.js:246:20 ExceptionFatal Context
```

**Comment by kimalec** [comment]
이슈 잘 못 발행함 것임
