### ISSUE TITLE
ionic splash 지원 방법 조사

### ISSUE THREAD

**Issue by skywlrl** [WizardFactory/TodayWeather#24]

**Comment by skywlrl** [comment]
**[Ionic splash 지원 방법]**
http://ionicframework.com/docs/cli/icon-splashscreen.html
https://blog.nraboy.com/2014/08/add-splash-screen-ionicframework-project/
* resources 폴더에 icon, splash 이미지 추가
 *  png, psd, ai 이미지를 지원
* $ ionic resources android
  * 추가한 psd 이미지가 resources\android 폴더에 해상도 별로 png 이미지가 생성
* Animated Image는 지원하지 않음

**[다른 방법]**
http://codepen.io/gwhickman/pen/zpDFG
* intro.html을 routerProvider로 추가하여 splash로 처리하고 있음
* 단일 이미지만 보여주는 Splash는 부족해보여 이 방법으로 Splash 추가 작업 진행 예정

**Comment by skywlrl** [comment]
**[ionic build 시 spawn 에러 발생]**
* ionic hooks add 명령어로 해결됨
```
WizardFactoryui-MacBook-Pro:client skywlrl$ ionic build android
Running command: /Users/skywlrl/WebstormProjects/TodayWeather/client/hooks/after_prepare/010_add_platform_class.js /Users/skywlrl/WebstormProjects/TodayWeather/client
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at Object.exports.spawn (child_process.js:995:9)
    at Object.exports.spawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:103:31)
    at runScriptViaChildProcessSpawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:189:23)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:115:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)

WizardFactoryui-MacBook-Pro:client skywlrl$ ionic hooks add
Adding in default Ionic Cordova hooks
Added default Ionic Cordova hooks
```

**Comment by skywlrl** [comment]
1. animated splash screen
