### ISSUE TITLE
js, html code optimize for production

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#348]
js, html code optimize for production

#178 은 여기서 일부 처리됨.
#206 전에 처리되어야 함.

https://www.airpair.com/ionic-framework/posts/production-ready-apps-with-ionic-framework

**Comment by kimalec** [comment]
https://www.airpair.com/ionic-framework/posts/production-ready-apps-with-ionic-framework

gulp-useref 에서 assets 는 없어진 것으로 보임.

https://www.npmjs.com/package/gulp-useref 에 아래와 같이 적혀 있음.
Assets inside the build blocks will be concatenated and passed through in a stream as well.

진행중에 아래와 같은 에러가 발생함. 경로 에러가 있는 것으로 보임.

```bash
Running command: /Users/aleckim/WebstormProjects/TodayWeather/client/hooks/after_prepare/040_move_dist_files_to_platforms.js /Users/aleckim/WebstormProjects/TodayWeather/client
Moving dist files to iOS platform
Moving dist files to Android platform
err
{ [Error: ENOENT, rename '/Users/aleckim/WebstormProjects/TodayWeather/client/platforms/ios/www/dist/index.html']
  errno: -2,
  code: 'ENOENT',
  path: '/Users/aleckim/WebstormProjects/TodayWeather/client/platforms/ios/www/dist/index.html' }
ERROR when moving index.html file to iOS platform
index.html file moved OK to Android platform
err
{ [Error: ENOENT, rename '/Users/aleckim/WebstormProjects/TodayWeather/client/platforms/ios/www/dist/dist_css']
  errno: -2,
  code: 'ENOENT',
  path: '/Users/aleckim/WebstormProjects/TodayWeather/client/platforms/ios/www/dist/dist_css' }
ERROR when moving CSS folder to iOS platform
err
{ [Error: ENOENT, rename '/Users/aleckim/WebstormProjects/TodayWeather/client/platforms/ios/www/dist/dist_js']
  errno: -2,
  code: 'ENOENT',
  path: '/Users/aleckim/WebstormProjects/TodayWeather/client/platforms/ios/www/dist/dist_js' }
ERROR when moving JS folder to iOS platform
CSS folder moved OK to Android platform
JS folder moved OK to Android platform
Running command: /Users/aleckim/WebstormProjects/TodayWeather/client/hooks/after_prepare/050_clean_obfuscation.js /Users/aleckim/WebstormProjects/TodayWeather/client
Running command: /Users/aleckim/WebstormProjects/TodayWeather/client/hooks/after_prepare/060_uglify.js /Users/aleckim/WebstormProjects/TodayWeather/client
cordova-uglify will always run by default, uncomment the line checking for the release flag otherwise
uglifying js file /Users/aleckim/WebstormProjects/TodayWeather/client/platforms/android/assets/www/dist_js/app.js
minifying css file /Users/aleckim/WebstormProjects/TodayWeather/client/platforms/android/assets/www/dist_css/styles.css
Running command: /Users/aleckim/WebstormProjects/TodayWeather/client/hooks/after_prepare/uglify.js /Users/aleckim/WebstormProjects/TodayWeather/client
Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at Object.exports.spawn (child_process.js:995:9)
    at Object.exports.spawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:108:31)
    at runScriptViaChildProcessSpawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:189:23)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:115:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
```

**Comment by kimalec** [comment]
cordova-uglify파일을 사용하면 파일 합치는 것은 안해주지만, 기본적인 minify는 해줌.

https://github.com/rossmartin/cordova-uglify

**Comment by kimalec** [comment]
파일 합쳐서 좀 더 최적화하는 것은 추후 진행하고, 본 이슈는 cordova-uglify 적용한 것으로 close하겠습니다.
