### ISSUE TITLE
routing에 shortRSS 적용하는 방법 개선

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#464]
지금은 getShort func안에서 getTownDataFromDB(modelCurrent,.. 해서 mergeShortWithRSS()하는데, getMid와 getMidRss처럼 분리하여, req.short 기준으로 업데이트 하게 개선하자.

**Comment by neoqmin** [comment]
코드 수정 후 테스트

1. db 초기화
2. node utils\initTownDataToMongo.js
3. town/서울특별시/마포구/공덕동 접속 후 아래와 같은 경고 발생
```javascirpt
info: > method=getMid, region=서울특별시, city=마포구
error: ~> getMidDataFromDB : there is no data
error: RM> no temp data
error:  method=getMid, region=서울특별시, city=마포구
c:\Projects\TodayWeather\server\controllers\midRssKmaController.js:21
            err = new Error("Fail to find midRss regId="+code.cityCode);
                                                         ^
ReferenceError: code is not defined
    at c:\Projects\TodayWeather\server\controllers\midRssKmaController.js:21:58
    at Query.<anonymous> (c:\Projects\TodayWeather\server\node_modules\mongoose\lib\query.js:2140:28)
    at c:\Projects\TodayWeather\server\node_modules\mongoose\node_modules\kareem\index.js:177:19
    at c:\Projects\TodayWeather\server\node_modules\mongoose\node_modules\kareem\index.js:109:16
    at process._tickCallback (node.js:355:11)
```
