### ISSUE TITLE
DB gather - mongoDB 서버와 접속이 끊기는 현상

### ISSUE THREAD

**Issue by pokers** [WizardFactory/TodayWeather#466]
서버 동작중 간헐적으로 ETimeout등의 error가 발생하면서 mongodb 서버와 접속이 끊기는 현상이 있음.
접속이 끊겼을때 retry하는 기능 추가 필요.

**Comment by pokers** [comment]
error 발생 시 로그.
~~~~~~~
Tue Dec 29 2015 05:04:36 GMT-0500 (EST): Node server started on 127.9.27.129:8080 ...
error: Could not connect to MongoDB! mongodb://todayweather:wzd1107@ds051524.mongolab.com:51524/todayweather
error:  Error: connect ETIMEDOUT
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)
info: C> +++ GET CURRENT INFO :  date=20151229, time=1900
~~~~~~~

**Comment by kimalec** [comment]
이번에 mongoose version 올렸어요. 봐서 node version도 한번 업데이트 해야 할꺼 같아요.

**Comment by kimalec** [comment]
아래와 로그와 함께 연결이 끊어졌음.
```js
info: keep alive : http://127.0.0.1:8080
error: Could not connect to MongoDB! mongodb://MONGOLAB_URL
error:  Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
info: check time and push task
```

**Comment by kimalec** [comment]
setting bufferMaxEntries to 2 still doesn't solve problem and the requests are buffered and occurs on reconnect.
```js
var options = {
    db: {
        bufferMaxEntries: 2
    },
    server: {
        socketOptions: {
            keepAlive: true,
            connectTimeoutMS: 2000
        },
        auto_reconnect: true
    }
}
MongoClient.connect(url, options, function(err, _db) {
```

http://stackoverflow.com/questions/29895946/how-to-handle-connection-problems-in-node-mongodb-native

**Comment by kimalec** [comment]
MongoLab recommended mongoose connection options
```js
/* 
 * Mongoose by default sets the auto_reconnect option to true.
 * We recommend setting socket options at both the server and replica set level.
 * We recommend a 30 second connection timeout because it allows for 
 * plenty of time in most operating environments.
 */
var options = { server: { socketOptions: { keepAlive: 1, connectTimeoutMS: 30000 } }, 
                replset: { socketOptions: { keepAlive: 1, connectTimeoutMS : 30000 } } }; 
```
https://gist.github.com/mongolab-org/9959376

**Comment by kimalec** [comment]
이후에 발생하는 경우 본적없으므로 close합니다.
