### ISSUE TITLE
실제 데이터가 존재하지만 에러나는 경우들이 있음.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#487]
실제 데이터가 존재하지만 에러나는 경우들이 있으며, 다시 요청하면 정상적으로 전달됨.

```js
info: ## method=/:region/:city/:town, region=경기도, city=성남시분당구, town=야탑3동
Error: Not Found
    at /var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/app.js:105:13
    at Layer.handle [as handle_request] (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:312:13)
    at /var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:330:12)
    at next (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:271:10)
    at /var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:618:15
    at next (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:176:3)
    at router (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:312:13)
    at /var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:330:12)
    at next (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:271:10)
    at SendStream.error (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/node_modules/serve-static/index.js:120:7)
Error: Not Found
    at /var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/app.js:105:13
    at Layer.handle [as handle_request] (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:312:13)
    at /var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:330:12)
    at next (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:271:10)
    at /var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:618:15
    at next (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:176:3)
    at router (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:312:13)
    at /var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:330:12)
    at next (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/lib/router/index.js:271:10)
    at SendStream.error (/var/lib/openshift/56868dc189f5cf8f690001e9/app-root/runtime/repo/node_modules/express/node_modules/serve-static/index.js:120:7)
```

**Comment by kimalec** [comment]
info와 not found는 다른 경우임. 에러 아님.
