### ISSUE TITLE
ECONNRESET 로 멈추는 문제.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#523]
17일 15시부터 socket error이후에 tasks만 증가하서 처리 되지 않고 있었음.
keep alive 제거?
```
info: check time and push task
info: wait 0 tasks
info: keep alive : http://127.0.0.1:8080
error:  Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
error:  Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
```

**Comment by kimalec** [comment]
#492 에서 keep alive 제거됨.
