### ISSUE TITLE
Add in-app purchases

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#524]
#189 일환으로 사용자의 선택 폭을 넓히기 위해 광고 제거용 in-app purchases 추가.

확인할 사항
auto-renewable subscription 가능한가?
구독 및 결제 된 것을 확인할 방법은 무엇인가?

참고
http://www.joshmorony.com/how-to-create-ios-in-app-purchases-with-phonegap-build/
https://blog.nraboy.com/2014/09/making-ios-app-purchases-ionicframework/

**Comment by kimalec** [comment]
https://blog.nraboy.com/2014/08/making-android-app-purchases-ionicframework/

**Comment by kimalec** [comment]
https://github.com/j3k0/cordova-plugin-purchase - windows, iOS, android 3개 지원

**Comment by kimalec** [comment]
http://blog.weirdx.io/post/25370 - 애플 인앱결제 검증 웹 서비스 제작

**Comment by kimalec** [comment]
IOS Account holder name은 꼭 영어로 해야 하는데, 은행에 확인필요.

http://blog.yagom.net/15

**Comment by kimalec** [comment]
W-8BEN 작성을 위해 EIN을 받아야 함.
http://blog.yagom.net/15
http://mocona.tistory.com/72
http://www.econovation.co.kr/ecnvb/인앱결재-등록하기/

**Comment by kimalec** [comment]
http://westwoodforever.blogspot.kr/2012/11/google-play-in-app-billing.html

**Comment by kimalec** [comment]
https://developer.apple.com/in-app-purchase/In-App-Purchase-Guidelines.pdf

**Comment by kimalec** [comment]
구글의 경우, billing permission이 있는  apk를 올리면서 셋업이 시작됨.
판매자의 정확한 주소 및 정보가 셋업되어야 하고, 페이먼트의 은행계좌도 확인되어야 함.

**Comment by kimalec** [comment]
To test in-app billing, you need to publish your app to an alpha or beta channel in Google Play.
 alpha 릴리즈가 완료되는 시간이 대중없음. 

http://javaexpert.tistory.com/617
https://developer.android.com/intl/ko/google/play/billing/billing_testing.html#billing-testing-static

**Comment by kimalec** [comment]
https://www.npmjs.com/package/in-app-purchase - In-App-Purchase validation and subscription management for iOS, Android, Amazon, and Windows

**Comment by kimalec** [comment]
iOS를 결제 화면에 대한 스크린샷이 올라가야 ready to submit 상태가 됨.
ready to submit 상태가 되어야 test가 가능하다고 함.

**Comment by kimalec** [comment]
일차적으로 디바이스에 accountLevel 를 저장하여 재사용시에 사용자가 이미 프리미엄이상이면 광고가 제시되지 않도록 한다.

이후 구동하면서 accountLevel을 재 확인하고, 필요하면 광고를 생성하도록 한다.

하단 광고 on/off시에 동작 고려사항.

index.html bottom div를 제거, ion-content의 bottom을 100px로 설정,  tabs의  margin-bottom을 50px로 설정해야 함.
tabs의 경우 ion-tabs에 의해 생성되기 때문에, run time에서 tabs가 생성될때, 조정해야함.

**Comment by kimalec** [comment]
ios invalid product id
bank account가 입력되지 않아도, invalid product id로 표시됨.

아직 해결안되고 있음.

**Comment by kimalec** [comment]
contact, bank, tax 정보 추가된 이후 valid item에 로드되는 것 확인하였음.

```
InAppPurchase[js]: load ok: { valid:[{"id":"annually","title":"프리미엄","currency":"USD","description":"일년동안 광고없는 프리미엄 서비스입니다.","price":"US$2.19"}] invalid:[] }
```

구매요청시에 로그인 창나오는데, 시간이 오래걸렸음.

**Comment by kimalec** [comment]
구매 기간중에 자동결제에 따른 여러가지 팝업이 표시됨.

재 실행시에 구매한 사용자 확인됨.

영수증 확인 방법과, 사용기간확인, 구매 복원방법 조사 필요함.

**Comment by kimalec** [comment]
사용자 로그아웃하고, 앱 제거후 다시 설치하고 구매내역 복원하기 시도

구매 복원을 시도하면(refresh) receipt를 request하고 새로운 구매영수증을 받아오면서 복원됨.
이 과정에서 validation 확인을 추가 거치면 됨.

**Comment by kimalec** [comment]
http://savvyapps.com/blog/how-setup-test-auto-renewable-subscription-ios-app
http://savvyapps.com/blog/getting-started-with-auto-renewable-subscriptions-in-ios

The subscription duration is not managed for you by StoreKit, so you’ll need a way of calculating the duration at the point of purchase.
https://www.raywenderlich.com/36270/in-app-purchases-non-renewing-subscription-tutorial

**Comment by kimalec** [comment]
사용 기간은 https://www.npmjs.com/package/in-app-purchase 에서 제공할 수 있는듯함.

```
.getPurchaseData(response [object], options [*object]);
Returns a parsed purchase data as an array.
For apple and windows, the returned array may contain more than 1 purchase data.
For Windows purchase data and Apple iTunes (recurring subscription only), each purchase data in the array contains expirationDate.
For Google Play purchases (recurring subscription only), each purchase data in the array contains expirationDate only if you provide google play store information.
```

**Comment by kimalec** [comment]
https://support.apple.com/ko-kr/HT204530 - App 내 구입 상품 복원하기

**Comment by kimalec** [comment]
https://github.com/AlexDisler/cordova-plugin-inapppurchase 은 https://github.com/voltrue2/in-app-purchase 사용하여 validation을 체크하고 있음.

https://alexdisler.com/2016/03/20/validating-cordova-in-app-purchases-on-ios-and-android-using-nodejs/

**Comment by kimalec** [comment]
validation을 확인하기 위해서는 j3k0/cordova-plugin-purchase 의 경우 body.transaction이 있고
여기에는 appStoreReceipt, id, transactionReceipt, type 이 있다.
여기서 transactionReceipt를 app store server에 넘겨야 한다.

근데 항상 앞의 테스트에서는 id, transactionReceipt가 없었다. 좀 더 확인이 필요함.

**Comment by kimalec** [comment]
Non-renewing subscriptions differ from auto-renewable subscriptions in a few key ways. These differences give your app the flexibility to implement the correct behavior for your needs, as follows:

Your app is responsible for calculating the time period that the subscription is active and determining what content needs to be made available to the user.
Your app is responsible for detecting that a subscription is approaching its expiration date and prompting the user to renew the subscription by purchasing the product again.
Your app is responsible for making subscriptions available across all the user’s devices after they’re purchased and for letting users restore past purchases. For example, most subscriptions are provided by a server; your server would need some mechanism to identify users and associate subscription purchases with the user who purchased them.

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Products.html

**Comment by kimalec** [comment]
auto renewing subscription을 위한 password는 앱 내 구입의 공유암호임.

**Comment by kimalec** [comment]
https://github.com/j3k0/cordova-plugin-purchase/issues/431 ->  j3k0/cordova-plugin-purchase  의 서버쪽 코드 일부

**Comment by kimalec** [comment]
시작할때, refresh하면 안됨.
refresh를 위해서는 계정 정보가 필요함.
사용자가 로그인 상태가 아닌데도, 복구시에 아이디를 물어보지 않음.

**Comment by kimalec** [comment]
ios Non-Renewing Subscriptions 으로 validation check까지 구현 완료.
각 상태별, 광고 on/off 동작 확인함.

남은 사항
android Subscriptions 구현
각 에러 상황에 따른 팝업메세지 정리

**Comment by kimalec** [comment]
chart의 크기가 $hasTabs를 watch한 후에 생성되는데, 이때까지 TwAds의 값이 설정되기 전이라, 광고가 있는 경우에 차트가 너무 크게 만들어짐.

**Comment by kimalec** [comment]
AlexDisler/cordova-plugin-inapppurchase 이 android 6.0.1에서 정상 동작하지 않음.

Fail to nativeCall 발생함.

"Error retrieving SKU details"

android 4.4.2 에서 정상적으로 products를 가져올 수 있음.

**Comment by kimalec** [comment]
cordova 6.1.1로 업그레이드 이후 동작함.

**Comment by kimalec** [comment]
결제 오류를 방지할 수 있는 프로모션 코드 사용법 확인 필요.

**Comment by kimalec** [comment]
로그인이 필요하다는 메세지가 나오는데 이 경우는 계정동기화를 안한 경우에도 발생하므로 꼭 계정 동기화가 필요함.

가격이 세금을 제외한 가격이라도 되어 있지만, 가격이 2천원이면 1.77불이 됨.

**Comment by kimalec** [comment]
android error 종류
product 정보를 못가지고 오는 경우 - 애플리케이션용 라이선스 키 설정이 제대로 되지 않았음.
이 버전의 애플리케이션에서는 Google Play를 통한 결제를 사용할 수 없습니다. - release하고 sign해야 함.
로그인이 필요합니다. - 계정 연결문제로, licensing account에 등록되어 있지 않으면 발생함. 또한 계정이 디바이스에 동기화되어 있어야함, sign했지만, 알파나 베타 테스트로 등록하지 않았음.

**Comment by kimalec** [comment]
구매취소하는 경우에 앱에서는 바로 알수 없음. 프리미엄 사용자인 경우, 시작시에 체크 필요함.

**Comment by kimalec** [comment]
receipt정보를 저장하고, 앱이 실행될때, cancel되거나, refund되었는지 확인한다.

**Comment by kimalec** [comment]
**요일별 차트에서 크기 맞지 않는 경우 있음.**
**Renew 기능 필요** -> ios는 3일정도 이후(당일에 입금되지 않고, 사용자 변심을 고려한듯), 안드로이드는 만기일 한달 전에 표기.

**Comment by kimalec** [comment]
안드로이드
구독취소하고, 재구입하게 되는 경우, subscribe한 결과에 전달되는 receipt정보가 과거의 것이 오며, autoRenewing이 여전히 false상태임.

**Comment by kimalec** [comment]
labHelper.java의 있는 code 훝어봤을 때, 문제가 있어 보이지 않음.
http://developer.android.com/intl/ko/google/play/billing/billing_integrate.html

**Comment by kimalec** [comment]
https://github.com/WizardFactory/TodayWeather/issues/524#issuecomment-213910451 더 검토해야 함.

**Comment by kimalec** [comment]
http://stackoverflow.com/questions/36973831/android-in-app-re-subscription-testing 문의해봄.

**Comment by kimalec** [comment]
구독 단위 변경하고, "유료앱은 곧 출시 예정입니다." 코멘트 추가.

**Comment by kimalec** [comment]
갱신 시나리오 검토, 팝업 메세지 개선.

**Comment by kimalec** [comment]
crosswalk 추가시에 빌드 에러 발생함.

```
:transformClassesWithDexForArmv7Debug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
	at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:484)
	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:261)
	at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:473)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:161)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)


 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForArmv7Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 34.334 secs
Error: Error code 1 for command: /Users/aleckim/WebstormProjects/TodayWeather/client/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/aleckim/WebstormProjects/TodayWeather/client/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
```

**Comment by kimalec** [comment]
앱별 일년 구독 마무리되었음.
