### ISSUE TITLE
service에서 client 요청 처리시에 최대 10초 걸리는 문제.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#579]
service에서 client 요청을 처리하는 중에 가끔 최대 10초 걸리는 문제가 있음.

APM 분석에 따르면 처음 mongodb query에서 가끔 수초 걸리는 문제가 있음.

가끔 db query가 없는 경우에도 오래 걸리는 경우가 있어 service server를 openshift에서 aws beanstalk t2.small로 변경했지만, 10초까지 걸리는 경우가 나오지 않았지만, 7,8초 걸리는 경우가 있음.

![default](https://cloud.githubusercontent.com/assets/6895272/12605930/aced8680-c50c-11e5-96e9-1f942278e5e5.PNG)

**Comment by kimalec** [comment]
aws에 mongodb를 만들어서 비교해보든가, dynamoDb로 변경하는 방법을 고려

**Comment by kimalec** [comment]
이상증상
1. townList에 있는 동임에도 불구하고, convertGeocode로 넘어감. 나중에 브라우져로 재시도해보면 잘 찾아짐. 여러개의 요청이 올때 문제가 발생하는 것으로 보이는데 확실하지 않음.
2. convertGeocode에서 못 찾아 에러가 발생함에도 불구하고 정상처럼 계속 동작함.

```
method=getShort, region=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C, city=%EC%A4%91%EA%B5%AC, town=%EA%B4%91%ED%9D%AC%EB%8F%99
error: ## Error!!! method=convertGeocode, first=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C, second=%EC%A4%91%EA%B5%AC, third=%EA%B4%91%ED%9D%AC%EB%8F%99, url=https://apis.daum.net/local/geo/addr2coord?apikey=6d0116e2c49361cb75eaf12f665e6360&q=%25EC%2584%259C%25EC%259A%25B8%25ED%258A%25B9%25EB%25B3%2584%25EC%258B%259C%25EC%25A4%2591%25EA%25B5%25AC%25EA%25B4%2591%25ED%259D%25AC%25EB%258F%2599&output=json
error: ~> getDataFromDB : there is no data
error:  Error: there is no data
    at /var/app/current/routes/routeTownForecast.js:519:24
    at Query.<anonymous> (/var/app/current/node_modules/mongoose/lib/query.js:2147:28)
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at process._tickCallback (node.js:355:11)
error: ## Error!!! method=convertGeocode, first=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C, second=%EC%A4%91%EA%B5%AC, third=%EA%B4%91%ED%9D%AC%EB%8F%99, url=https://apis.daum.net/local/geo/addr2coord?apikey=6d0116e2c49361cb75eaf12f665e6360&q=%25EC%2584%259C%25EC%259A%25B8%25ED%258A%25B9%25EB%25B3%2584%25EC%258B%259C%25EC%25A4%2591%25EA%25B5%25AC%25EA%25B4%2591%25ED%259D%25AC%25EB%258F%2599&output=json
error: ~> getDataFromDB : there is no data
error: error to get short RSS
info: > method=getShortest, region=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C, city=%EC%A4%91%EA%B5%AC, town=%EA%B4%91%ED%9D%AC%EB%8F%99
error: ## Error!!! method=convertGeocode, first=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C, second=%EC%A4%91%EA%B5%AC, third=%EA%B4%91%ED%9D%AC%EB%8F%99, url=https://apis.daum.net/local/geo/addr2coord?apikey=6d0116e2c49361cb75eaf12f665e6360&q=%25EC%2584%259C%25EC%259A%25B8%25ED%258A%25B9%25EB%25B3%2584%25EC%258B%259C%25EC%25A4%2591%25EA%25B5%25AC%25EA%25B4%2591%25ED%259D%25AC%25EB%258F%2599&output=json
error: ~> getDataFromDB : there is no data
error:  Error: there is no data
    at /var/app/current/routes/routeTownForecast.js:519:24
    at Query.<anonymous> (/var/app/current/node_modules/mongoose/lib/query.js:2147:28)
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at process._tickCallback (node.js:355:11)
info: > method=getCurrent, region=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C, city=%EC%A4%91%EA%B5%AC, town=%EA%B4%91%ED%9D%AC%EB%8F%99
error: ## Error!!! method=convertGeocode, first=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C, second=%EC%A4%91%EA%B5%AC, third=%EA%B4%91%ED%9D%AC%EB%8F%99, url=https://apis.daum.net/local/geo/addr2coord?apikey=6d0116e2c49361cb75eaf12f665e6360&q=%25EC%2584%259C%25EC%259A%25B8%25ED%258A%25B9%25EB%25B3%2584%25EC%258B%259C%25EC%25A4%2591%25EA%25B5%25AC%25EA%25B4%2591%25ED%259D%25AC%25EB%258F%2599&output=json
error: ~> getDataFromDB : there is no data
error:  Error: there is no data
    at /var/app/current/routes/routeTownForecast.js:519:24
    at Query.<anonymous> (/var/app/current/node_modules/mongoose/lib/query.js:2147:28)
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at process._tickCallback (node.js:355:11)
warn:  Error: Fail to find current weather
    at getKeco (/var/app/current/routes/routeTownForecast.js:2080:19)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
    at /var/app/current/routes/routeTownForecast.js:1762:32
    at /var/app/current/routes/routeTownForecast.js:519:21
    at Query.<anonymous> (/var/app/current/node_modules/mongoose/lib/query.js:2147:28)
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at process._tickCallback (node.js:355:11)
info: > method=getMid, region=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C, city=%EC%A4%91%EA%B5%AC
error: RM> there is no code
error:  method=getMid, region=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C, city=%EC%A4%91%EA%B5%AC
error:  Error: Fail to find code table 
    at Manager.getRegIdByTown (/var/app/current/controllers/controllerManager.js:98:12)
    at getMidRss (/var/app/current/routes/routeTownForecast.js:1809:17)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
    at /var/app/current/routes/routeTownForecast.js:1920:28
    at Manager.getRegIdByTown (/var/app/current/controllers/controllerManager.js:98:9)
    at getMid (/var/app/current/routes/routeTownForecast.js:1916:21)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
    at getKeco (/var/app/current/routes/routeTownForecast.js:2082:16)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
    at /var/app/current/routes/routeTownForecast.js:1762:32
    at /var/app/current/routes/routeTownForecast.js:519:21
    at Query.<anonymous> (/var/app/current/node_modules/mongoose/lib/query.js:2147:28)
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:177:19
error: ## Error!!! method=convertGeocode, first=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C, second=%EC%A4%91%EA%B5%AC, third=%EA%B4%91%ED%9D%AC%EB%8F%99, url=https://apis.daum.net/local/geo/addr2coord?apikey=6d0116e2c49361cb75eaf12f665e6360&q=%25EC%2584%259C%25EC%259A%25B8%25ED%258A%25B9%25EB%25B3%2584%25EC%258B%259C%25EC%25A4%2591%25EA%25B5%25AC%25EA%25B4%2591%25ED%259D%25AC%25EB%258F%2599&output=json
error: ~> getDataFromDB : there is no data
error:  Error: there is no data
    at /var/app/current/routes/routeTownForecast.js:519:24
    at Query.<anonymous> (/var/app/current/node_modules/mongoose/lib/query.js:2147:28)
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at process._tickCallback (node.js:355:11)
error:  Error: Unknown state sky=NaN pty=0
    at _convertSkyToKorStr (/var/app/current/routes/routeTownForecast.js:2207:15)
    at /var/app/current/routes/routeTownForecast.js:2264:27
    at Array.forEach (native)
    at _getDaySummaryListByShort (/var/app/current/routes/routeTownForecast.js:2255:22)
    at mergeMidWithShort (/var/app/current/routes/routeTownForecast.js:2412:30)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
    at /var/app/current/routes/routeTownForecast.js:2366:28
    at /var/app/current/routes/routeTownForecast.js:519:21
    at Query.<anonymous> (/var/app/current/node_modules/mongoose/lib/query.js:2147:28)
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at process._tickCallback (node.js:355:11)
error:  Error: Unknown state sky=NaN pty=0
    at _convertSkyToKorStr (/var/app/current/routes/routeTownForecast.js:2207:15)
    at /var/app/current/routes/routeTownForecast.js:2265:27
    at Array.forEach (native)
    at _getDaySummaryListByShort (/var/app/current/routes/routeTownForecast.js:2255:22)
    at mergeMidWithShort (/var/app/current/routes/routeTownForecast.js:2412:30)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
    at /var/app/current/routes/routeTownForecast.js:2366:28
    at /var/app/current/routes/routeTownForecast.js:519:21
    at Query.<anonymous> (/var/app/current/node_modules/mongoose/lib/query.js:2147:28)
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at process._tickCallback (node.js:355:11)
error:  Error: Unknown state sky=NaN pty=0
    at _convertSkyToKorStr (/var/app/current/routes/routeTownForecast.js:2207:15)
    at /var/app/current/routes/routeTownForecast.js:2264:27
    at Array.forEach (native)
    at _getDaySummaryListByShort (/var/app/current/routes/routeTownForecast.js:2255:22)
    at mergeMidWithShort (/var/app/current/routes/routeTownForecast.js:2412:30)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
    at /var/app/current/routes/routeTownForecast.js:2366:28
    at /var/app/current/routes/routeTownForecast.js:519:21
    at Query.<anonymous> (/var/app/current/node_modules/mongoose/lib/query.js:2147:28)
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at process._tickCallback (node.js:355:11)
error:  Error: Unknown state sky=NaN pty=0
    at _convertSkyToKorStr (/var/app/current/routes/routeTownForecast.js:2207:15)
    at /var/app/current/routes/routeTownForecast.js:2265:27
    at Array.forEach (native)
    at _getDaySummaryListByShort (/var/app/current/routes/routeTownForecast.js:2255:22)
    at mergeMidWithShort (/var/app/current/routes/routeTownForecast.js:2412:30)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
    at /var/app/current/routes/routeTownForecast.js:2366:28
    at /var/app/current/routes/routeTownForecast.js:519:21
    at Query.<anonymous> (/var/app/current/node_modules/mongoose/lib/query.js:2147:28)
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at process._tickCallback (node.js:355:11)
error:  Error: Unknown state sky=NaN pty=0
    at _convertSkyToKorStr (/var/app/current/routes/routeTownForecast.js:2207:15)
    at /var/app/current/routes/routeTownForecast.js:2264:27
    at Array.forEach (native)
    at _getDaySummaryListByShort (/var/app/current/routes/routeTownForecast.js:2255:22)
    at mergeMidWithShort (/var/app/current/routes/routeTownForecast.js:2412:30)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
    at /var/app/current/routes/routeTownForecast.js:2366:28
    at /var/app/current/routes/routeTownForecast.js:519:21
    at Query.<anonymous> (/var/app/current/node_modules/mongoose/lib/query.js:2147:28)
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at process._tickCallback (node.js:355:11)
error:  Error: Unknown state sky=NaN pty=0
    at _convertSkyToKorStr (/var/app/current/routes/routeTownForecast.js:2207:15)
    at /var/app/current/routes/routeTownForecast.js:2265:27
    at Array.forEach (native)
    at _getDaySummaryListByShort (/var/app/current/routes/routeTownForecast.js:2255:22)
    at mergeMidWithShort (/var/app/current/routes/routeTownForecast.js:2412:30)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
    at /var/app/current/routes/routeTownForecast.js:2366:28
    at /var/app/current/routes/routeTownForecast.js:519:21
    at Query.<anonymous> (/var/app/current/node_modules/mongoose/lib/query.js:2147:28)
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at process._tickCallback (node.js:355:11)
info: > method=mergeByShortest, region=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C, city=%EC%A4%91%EA%B5%AC, town=%EA%B4%91%ED%9D%AC%EB%8F%99
error: ## Error!!! method=convertGeocode, first=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C, second=%EC%A4%91%EA%B5%AC, third=%EA%B4%91%ED%9D%AC%EB%8F%99, url=https://apis.daum.net/local/geo/addr2coord?apikey=6d0116e2c49361cb75eaf12f665e6360&q=%25EC%2584%259C%25EC%259A%25B8%25ED%258A%25B9%25EB%25B3%2584%25EC%258B%259C%25EC%25A4%2591%25EA%25B5%25AC%25EA%25B4%2591%25ED%259D%25AC%25EB%258F%2599&output=json
error: ~> getDataFromDB : there is no data
error:  Error: there is no data
    at /var/app/current/routes/routeTownForecast.js:519:24
    at Query.<anonymous> (/var/app/current/node_modules/mongoose/lib/query.js:2147:28)
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at process._tickCallback (node.js:355:11)
info: ## method=/:region/:city/:town, region=%EC%84%9C%EC%9A%B8%ED%8A%B9%EB%B3%84%EC%8B%9C, city=%EC%A4%91%EA%B5%AC, town=%EA%B4%91%ED%9D%AC%EB%8F%99
info: + townForecast > request | Time[ 2016-01-28T06:29:30.436Z ]
```

**Comment by kimalec** [comment]
아래 array에 있는 함수들이 병렬로 처리되므로, 문제 될 수 있음.
특히 mergeXXXX 들은 순차적으로 처리되는 걸로 생각하고 만들어졌음.

```
router.get('/:region/:city/:town', [getShort, getShortRss, getShortest,
                                    getCurrent, getKeco, getMid,
                                    getMidRss, getPastMid, mergeMidWithShort,
                                    mergeByShortest], function(req, res) {
```

**Comment by kimalec** [comment]
순차적으로 처리되는 것이 맞음. error 메세지 출력이 늦어서 착각한 것임.

**Comment by kimalec** [comment]
아래 로그를 보면 getShort가 6초 걸림.

```
» 29 Jan 2016 16:43:45.779 2016-01-29T07:43:45.743Z info + townForecast > request | Time[ 2016-01-29T07:43:45.742Z ]
» 29 Jan 2016 16:43:45.856 2016-01-29T07:43:45.743Z info > {"method":"getShort","region":"인천광역시","city":"계양구","town":"계산1동"}
» 29 Jan 2016 16:43:51.474 2016-01-29T07:43:51.437Z info > {"method":"getShortRss","region":"인천광역시","city":"계양구","town":"계산1동"}
```

**Comment by kimalec** [comment]
aws t2.small에 mongodb 올려서 test 해보는 중.

참고
https://docs.mongodb.org/ecosystem/platforms/amazon-ec2/
https://docs.mongodb.org/v3.0/tutorial/install-mongodb-on-amazon/
http://stackoverflow.com/questions/18412850/cannot-connect-to-mongodb-using-machine-ip

**Comment by kimalec** [comment]
Average latency in seconds during last 8 hours
<img width="527" alt="2016-02-01 08 42 38" src="https://cloud.githubusercontent.com/assets/6895272/12706089/5816f4d6-c8c0-11e5-9829-507a845bb32b.png">

Average time during last 6 hours
<img width="680" alt="2016-02-01 08 47 34" src="https://cloud.githubusercontent.com/assets/6895272/12706091/7dcfdbac-c8c0-11e5-8c50-12a8cdbb388e.png">

**Comment by kimalec** [comment]
현재는 테스트용으로 간결히 만든 것이므로, 계정등 완벽설정이 필요함.

**Comment by kimalec** [comment]
13시 54분에 1.30 초 걸린 경우가 있었음. 로그상 getCurrent와, getKeco에 지연이 있었음.

```
» 5 Feb 2016 13:54:14.743 2016-02-05T04:54:14.660Z info > {"method":"getCurrent","region":"서울특별시","city":"마포구","town":"상암동"}
» 5 Feb 2016 13:54:16.119 2016-02-05T04:54:16.078Z info > {"method":"getKeco","region":"서울특별시","city":"마포구","town":"상암동"}
» 5 Feb 2016 13:54:16.195 2016-02-05T04:54:16.082Z info > {"method":"getMid","region":"서울특별시","city":"마포구"}
» 5 Feb 2016 13:54:16.195 2016-02-05T04:54:16.090Z info > {"method":"getMidRss","region":"서울특별시","city":"마포구"}
```

**Comment by kimalec** [comment]
mongolab 지연 문제에 따른 것으로 확인되었으며, 추후 문제가 발생시에 따로 오픈해서 진행
