### ISSUE TITLE
부산지역 500 error

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#580]
부산지역 500 error 발생

```
info: > method=getMid, region=부산광역시, city=부산진구
error: ~> getMidDataFromDB : there is no data
error: RM> no forecast data
error:  method=getMid, region=부산광역시, city=부산진구
/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:158
      throw err
            ^
TypeError: Cannot read property 'date' of undefined
    at /var/app/current/controllers/midRssKmaController.js:52:64
    at Array.forEach (native)
    at /var/app/current/controllers/midRssKmaController.js:51:28
    at /var/app/current/controllers/midRssKmaController.js:25:9
    at Query.<anonymous> (/var/app/current/node_modules/mongoose/lib/query.js:2147:28)
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:177:19
    at /var/app/current/node_modules/mongoose/node_modules/kareem/index.js:109:16
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at process._tickCallback (node.js:355:11)
```

**Comment by kimalec** [comment]
error 가 두가지 임. 
1. midData가 없는 문제.
2. midRss overwirte할 때 예외처리 없는 문제.

**Comment by kimalec** [comment]
1번 문제는 region.csv의 mistyping, 2번문제는 array의 length check 안한 문제.
