### ISSUE TITLE
VersionError: No matching document found

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#682]
data save하다보면 VersionError가 발생함.

```js
error:  VersionError: No matching document found.
    at /var/app/current/node_modules/mongoose/lib/model.js:214:19
    at /var/app/current/node_modules/mongoose/lib/model.js:167:9
    at wrappedCallback (/var/app/current/node_modules/newrelic/lib/instrumentation/mongodb.js:215:25)
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at wrappedCallback (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:417:66)
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at handleCallback (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/utils.js:96:12)
    at /var/app/current/node_modules/mongoose/node_modules/mongodb/lib/collection.js:1010:5
    at commandCallback (/var/app/current/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1142:9)
    at Callbacks.emit (/var/app/current/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:116:3)
    at null.messageHandler (/var/app/current/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:291:23)
    at Socket.<anonymous> (/var/app/current/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:285:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by kimalec** [comment]
http://stackoverflow.com/questions/21099904/node-mongoose-on-save-versionerror-no-matching-document-found

https://github.com/Automattic/mongoose/issues/3211

**Comment by kimalec** [comment]
lifeindex를 갱신하기 위해서 townList를 쓰는데 여기 있는 areaNo는 중복되어 있기 때문에 발생한 문제였음.
