### ISSUE TITLE
ultrv 가지고 오다가 행업 걸리는 문제.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#683]
ultrv 가지고 오다가 행업 걸리는 문제.

```
error:  VersionError: No matching document found.
    at /var/app/current/node_modules/mongoose/lib/model.js:214:19
    at /var/app/current/node_modules/mongoose/lib/model.js:167:9
    at wrappedCallback (/var/app/current/node_modules/newrelic/lib/instrumentation/mongodb.js:215:25)
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at wrappedCallback (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:417:66)
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at handleCallback (/var/app/current/node_modules/mongoose/node_modules/mongodb/lib/utils.js:96:12)
    at /var/app/current/node_modules/mongoose/node_modules/mongodb/lib/collection.js:1010:5
    at commandCallback (/var/app/current/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1142:9)
    at Callbacks.emit (/var/app/current/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:116:3)
    at null.messageHandler (/var/app/current/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:291:23)
    at Socket.<anonymous> (/var/app/current/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:285:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
unknown log level: err
warn: retry to get kma life index failList.length=164 retryCount=29
unknown log level: warning
info: Fail to find areaNo=4822069500 so get first time
info: areaNo=4812964000 life index data already updated skip ultrv lateUpdateDate=2016032707
info: areaNo=4719052000 life index data already updated skip ultrv lateUpdateDate=2016032707
info: areaNo=4514064600 life index data already updated skip ultrv lateUpdateDate=2016032707
warn: Search result is nothing but continue getting data index=ultrv ErrMsg=검색결과가 없습니다. [4161025600]
unknown log level: warning
warn: Search result is nothing but continue getting data index=ultrv ErrMsg=검색결과가 없습니다. [4119753000]
unknown log level: warning
warn: Search result is nothing but continue getting data index=ultrv ErrMsg=검색결과가 없습니다. [4822069500]
unknown log level: warning
error: areaNo=4141054000 ultrv life index has not updated yet lastUpdateDate=2016032707
unknown log level: err
warn: response status Code=503 indexName=ultrv area{"areaNo":"4128155000","gCoord":{"lon":126.83,"lat":37.65},"mCoord":{"my":128,"mx":57},"town":{"third":"성사2동","second":"고양시덕양구","first":"경기도"},"__v":0,"kecoStationName":"행신동","tmCoord":{"x":184928.18898073985,"y":460861.0036582281}}
unknown log level: warning
warn: response status Code=503 indexName=ultrv area{"areaNo":"4129056000","gCoord":{"lon":127,"lat":37.43},"mCoord":{"my":124,"mx":60},"town":{"third":"문원동","second":"과천시","first":"경기도"},"__v":0,"kecoStationName":"별양동","tmCoord":{"x":199930.12703932155,"y":436429.6538177701}}
unknown log level: warning
warn: response status Code=503 indexName=ultrv area{"areaNo":"4283025000","gCoord":{"lon":128.62,"lat":38.08},"mCoord":{"my":138,"mx":88},"town":{"third":"양양읍","second":"양양군","first":"강원도"},"__v":0,"kecoStationName":"간성읍","tmCoord":{"x":342070.9278919352,"y":509812.06450524647}}
unknown log level: warning
warn: response status Code=503 indexName=ultrv area{"areaNo":"4219060500","gCoord":{"lon":129.02,"lat":37.1},"mCoord":{"my":117,"mx":95},"town":{"third":"구문소동","second":"태백시","first":"강원도"},"__v":0,"kecoStationName":"남양동1","tmCoord":{"x":379508.9147445312,"y":401712.09178511193}}
unknown log level: warning
warn: response status Code=503 indexName=ultrv area{"areaNo":"4117156000","gCoord":{"lon":126.93,"lat":37.39},"mCoord":{"my":123,"mx":59},"town":{"third":"안양6동","second":"안양시만안구","first":"경기도"},"__v":0,"kecoStationName":"안양6동","tmCoord":{"x":193731.156410401,"y":431992.6032723943}}
unknown log level: warning
warn: response status Code=503 indexName=ultrv area{"areaNo":"4111160000","gCoord":{"lon":127.02,"lat":37.29},"mCoord":{"my":121,"mx":61},"town":{"third":"연무동","second":"수원시장안구","first":"경기도"},"__v":0,"kecoStationName":"광교동","tmCoord":{"x":201703.3418028979,"y":420891.8731623157}}
unknown log level: warning
warn: response status Code=503 indexName=ultrv area{"areaNo":"4885042000","gCoord":{"lon":127.79,"lat":34.96},"mCoord":{"my":70,"mx":75},"town":{"third":"금성면","second":"하동군","first":"경상남도"},"__v":0,"kecoStationName":"태인동","tmCoord":{"x":272079.88793642115,"y":162633.9580648616}}
unknown log level: warning
warn: response status Code=503 indexName=ultrv area{"areaNo":"4514062000","gCoord":{"lon":126.94,"lat":35.94},"mCoord":{"my":91,"mx":60},"town":{"third":"송학동","second":"익산시","first":"전라북도"},"__v":0,"kecoStationName":"모현동","tmCoord":{"x":194513.6071744766,"y":271082.2542183767}}
unknown log level: warning
```

**Comment by kimalec** [comment]
항상발생하는 것은 아니고, 이틀에 한번 정도 발생하고 있음.

**Comment by kimalec** [comment]
lifeIndex 저장하는 오류 해결이후로 발생하지 않음.
save시에 꼬이면 발생하는 것으로 추정됨.
